<?php

/**
 * Global Helper Functions
 */

if (!function_exists('app')) {
    function app(): \App\Core\App
    {
        return \App\Core\App::getInstance();
    }
}

if (!function_exists('db')) {
    function db(): \App\Core\Database
    {
        return app()->db();
    }
}

if (!function_exists('auth')) {
    function auth(): \App\Core\Auth
    {
        return app()->auth();
    }
}

if (!function_exists('config')) {
    function config(string $key, $default = null)
    {
        return app()->config($key, $default);
    }
}

if (!function_exists('url')) {
    function url(string $path = ''): string
    {
        return app()->url($path);
    }
}

if (!function_exists('redirect')) {
    function redirect(string $url): void
    {
        header("Location: {$url}");
        exit;
    }
}

if (!function_exists('old')) {
    function old(string $key, $default = ''): string
    {
        return htmlspecialchars($_SESSION['old_input'][$key] ?? $default);
    }
}

if (!function_exists('csrf_token')) {
    function csrf_token(): string
    {
        if (!isset($_SESSION['csrf_token'])) {
            $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
        }
        return $_SESSION['csrf_token'];
    }
}

if (!function_exists('csrf_field')) {
    function csrf_field(): string
    {
        return '<input type="hidden" name="_token" value="' . csrf_token() . '">';
    }
}

if (!function_exists('method_field')) {
    function method_field(string $method): string
    {
        return '<input type="hidden" name="_method" value="' . strtoupper($method) . '">';
    }
}

if (!function_exists('e')) {
    function e(?string $value): string
    {
        return htmlspecialchars($value ?? '', ENT_QUOTES, 'UTF-8');
    }
}

if (!function_exists('format_date')) {
    function format_date(?string $date, string $format = 'M j, Y'): string
    {
        if (!$date) return '';
        return date($format, strtotime($date));
    }
}

if (!function_exists('format_datetime')) {
    function format_datetime(?string $date, string $format = 'M j, Y g:i A'): string
    {
        if (!$date) return '';
        return date($format, strtotime($date));
    }
}

if (!function_exists('time_ago')) {
    function time_ago(string $datetime): string
    {
        $time = strtotime($datetime);
        $diff = time() - $time;

        if ($diff < 60) {
            return 'just now';
        } elseif ($diff < 3600) {
            $mins = floor($diff / 60);
            return $mins . ' min' . ($mins > 1 ? 's' : '') . ' ago';
        } elseif ($diff < 86400) {
            $hours = floor($diff / 3600);
            return $hours . ' hour' . ($hours > 1 ? 's' : '') . ' ago';
        } elseif ($diff < 604800) {
            $days = floor($diff / 86400);
            return $days . ' day' . ($days > 1 ? 's' : '') . ' ago';
        } else {
            return format_date($datetime);
        }
    }
}

if (!function_exists('truncate')) {
    function truncate(string $text, int $length = 100, string $suffix = '...'): string
    {
        if (strlen($text) <= $length) {
            return $text;
        }
        return substr($text, 0, $length) . $suffix;
    }
}

if (!function_exists('flash')) {
    function flash(string $type, string $message): void
    {
        $_SESSION["flash_{$type}"] = $message;
    }
}

if (!function_exists('get_flash')) {
    function get_flash(string $type): ?string
    {
        $message = $_SESSION["flash_{$type}"] ?? null;
        unset($_SESSION["flash_{$type}"]);
        return $message;
    }
}

if (!function_exists('app_lang')) {
    function app_lang(): string
    {
        static $resolved = null;
        if ($resolved !== null) {
            return $resolved;
        }

        $allowed = ['en', 'km'];
        $requested = strtolower((string)($_GET['lang'] ?? ''));
        $sessionLang = strtolower((string)($_SESSION['lang'] ?? ''));
        $cookieLang = strtolower((string)($_COOKIE['lang'] ?? ''));

        if (in_array($requested, $allowed, true)) {
            $resolved = $requested;
            if (session_status() === PHP_SESSION_ACTIVE) {
                $_SESSION['lang'] = $resolved;
            }
            setcookie('lang', $resolved, time() + (86400 * 365), '/');
            return $resolved;
        }

        if (in_array($sessionLang, $allowed, true)) {
            $resolved = $sessionLang;
            return $resolved;
        }

        if (in_array($cookieLang, $allowed, true)) {
            $resolved = $cookieLang;
            if (session_status() === PHP_SESSION_ACTIVE) {
                $_SESSION['lang'] = $resolved;
            }
            return $resolved;
        }

        $resolved = 'en';
        return $resolved;
    }
}

if (!function_exists('lang_url')) {
    function lang_url(string $lang): string
    {
        $lang = strtolower($lang);
        if (!in_array($lang, ['en', 'km'], true)) {
            $lang = 'en';
        }

        $uri = $_SERVER['REQUEST_URI'] ?? '/';
        $parts = parse_url($uri);
        $path = $parts['path'] ?? '/';
        $query = [];

        if (!empty($parts['query'])) {
            parse_str($parts['query'], $query);
        }

        $query['lang'] = $lang;
        $queryString = http_build_query($query);

        return $path . ($queryString ? '?' . $queryString : '');
    }
}

if (!function_exists('translations')) {
    function translations(): array
    {
        static $messages = null;
        if ($messages !== null) {

        return $messages;
        }

        $messages = [
            'en' => [
                'app_support_desk' => 'Support Desk',
                'app_support_portal' => 'Support Portal',
                'language' => 'Language',
                'english' => 'English',
                'khmer' => 'Khmer',
                'dashboard' => 'Dashboard',
                'tickets' => 'Tickets',
                'my_tickets' => 'My Tickets',
                'all_tickets' => 'All Tickets',
                'new_ticket' => 'New Ticket',
                'create_ticket' => 'Create Ticket',
                'knowledge_base' => 'Knowledge Base',
                'analytics' => 'Analytics',
                'settings' => 'Settings',
                'general' => 'General',
                'categories' => 'Categories',
                'users' => 'Users',
                'email' => 'Email',
                'telegram' => 'Telegram',
                'canned_responses' => 'Canned Responses',
                'sla_configuration' => 'SLA Configuration',
                'notifications' => 'Notifications',
                'mark_all_read' => 'Mark all read',
                'desktop_notifications' => 'Desktop Notifications',
                'enabled' => 'Enabled',
                'blocked' => 'Blocked',
                'not_set' => 'Not Set',
                'enable_desktop_notifications' => 'Enable Desktop Notifications',
                'no_notifications' => 'No notifications',
                'logout' => 'Logout',
                'login' => 'Login',
                'register' => 'Register',
                'welcome_back' => 'Welcome Back',
                'email_address' => 'Email Address',
                'password' => 'Password',
                'sign_in' => 'Sign In',
                'dont_have_account' => "Don't have an account?",
                'create_one' => 'Create one',
                'create_your_account' => 'Create Your Account',
                'company_name' => 'Company Name',
                'your_name' => 'Your Name',
                'confirm_password' => 'Confirm Password',
                'create_account' => 'Create Account',
                'already_have_account' => 'Already have an account?',
                'sign_in_link' => 'Sign in',
                'modern_ai_ticketing_system' => 'Modern AI-Powered Ticketing System',
                'all_rights_reserved' => 'All rights reserved.',
                'all' => 'All',
                'my_profile' => 'My Profile',
                'open_tickets' => 'Open Tickets',
                'urgent' => 'urgent',
                'in_progress' => 'In Progress',
                'pending' => 'Pending',
                'active' => 'active',
                'resolved_today' => 'Resolved Today',
                'unassigned' => 'Unassigned',
                'sla_breach_alert' => 'SLA Breach Alert',
                'ticket_requires_attention' => ':count ticket(s) require immediate attention (ITIL Standard)',
                'view_analytics' => 'View Analytics',
                'response_sla_breached' => 'Response SLA BREACHED',
                'resolution_sla_breached' => 'Resolution SLA BREACHED',
                'sla_breach_in_minutes' => 'SLA breach in :minutes minutes',
                'more_tickets_near_sla' => '+ :count more tickets near SLA breach',
                'response_on_time' => 'Response On Time',
                'resolution_on_time' => 'Resolution On Time',
                'response_overdue' => 'Response Overdue',
                'resolution_overdue' => 'Resolution Overdue',
                'needs_immediate_response' => 'Needs immediate response',
                'needs_immediate_resolution' => 'Needs immediate resolution',
                'breached' => 'breached',
                'recent_tickets' => 'Recent Tickets',
                'view_all' => 'View All',
                'no_tickets_yet' => 'No tickets yet',
                'by_category' => 'By Category',
                'open' => 'open',
                'recent_activity' => 'Recent Activity',
                'total_tickets' => ':count total tickets',
                'filter' => 'Filter',
                'clear' => 'Clear',
                'search_tickets' => 'Search tickets...',
                'all_status' => 'All Status',
                'all_priority' => 'All Priority',
                'all_categories' => 'All Categories',
                'all_agents' => 'All Agents',
                'no_tickets_found' => 'No tickets found',
                'try_adjusting_filters' => 'Try adjusting your filters or create a new ticket.',
                'source' => 'Source',
                'page_of' => 'Page :current of :total',
                'previous' => 'Previous',
                'next' => 'Next',
                'submit_support_request' => 'Submit a Support Request',
                'describe_issue_support' => "Describe your issue and we'll get back to you as soon as possible.",
                'subject' => 'Subject',
                'description' => 'Description',
                'category' => 'Category',
                'select_category_optional' => 'Select a category (optional)',
                'we_categorize_for_you' => "Don't worry if unsure - we'll categorize it for you.",
                'brief_summary_issue' => 'Brief summary of your issue',
                'provide_detail_issue' => 'Please provide as much detail as possible...',
                'include_steps_errors' => 'Include steps to reproduce the issue, error messages, and screenshots if relevant.',
                'cancel' => 'Cancel',
                'submit_ticket' => 'Submit Ticket',
                'create_new_ticket' => 'Create New Ticket',
                'fill_ticket_details' => 'Fill in the details below to create a support ticket',
                'create_ticket_help_team' => 'Create a new ticket to get help from our support team.',
                'created_on' => 'Created on',
                'conversation' => 'Conversation',
                'support_team' => 'Support Team',
                'support' => 'Support',
                'attachments' => 'Attachments',
                'add_reply' => 'Add a Reply',
                'reply' => 'Reply',
                'type_your_message' => 'Type your message...',
                'attachments_optional' => 'Attachments (optional)',
                'click_to_upload' => 'Click to upload',
                'or_drag_drop' => 'or drag and drop',
                'images_docs_limit' => 'Images, PDFs, Documents up to 10MB each',
                'send_reply' => 'Send Reply',
                'internal_note' => 'Internal Note',
                'ticket_closed_notice' => 'This ticket has been closed. If you need further assistance, please create a new ticket.',
                'profile_settings' => 'Profile Settings',
                'update_account_info' => 'Update your account information',
                'full_name' => 'Full Name',
                'email_cannot_change' => 'Email cannot be changed',
                'phone_number' => 'Phone Number',
                'change_password' => 'Change Password',
                'leave_blank_keep_password' => 'Leave blank to keep current password',
                'current_password' => 'Current Password',
                'new_password' => 'New Password',
                'save_changes' => 'Save Changes',
                'telegram_connected' => 'Telegram Connected',
                'account_linked_telegram' => 'Your account is linked to Telegram',
                'connect_telegram' => 'Connect Telegram',
                'link_telegram_for_tickets' => 'Link your Telegram account to create and manage tickets via chat. Contact support for the bot link.',
                'properties' => 'Properties',
                'assign_to' => 'Assign To',
                'uncategorized' => 'Uncategorized',
                'requester' => 'Requester',
                'customer_satisfaction' => 'Customer Satisfaction',
                'customer_feedback' => 'Customer Feedback',
                'rated_on' => 'Rated on',
                'survey_sent_awaiting' => 'Survey sent, awaiting response',
                'sent_on' => 'Sent on',
                'activity' => 'Activity',
                'quick_responses' => 'Quick Responses',
                'select_canned_response' => 'Select a canned response...',
                'internal_note_hidden' => 'Internal note (hidden from customer)',
                'add_note' => 'Add Note',
                'auto_detect_ai' => 'Auto-detect (AI)',
                'leave_empty_ai_category' => 'Leave empty to let AI categorize',
                'priority' => 'Priority',
                'low' => 'Low',
                'medium' => 'Medium',
                'high' => 'High',
                'resolved' => 'Resolved',
                'closed' => 'Closed',
                'status' => 'Status',
                'requester_info' => 'Requester',
                'ai_powered_categorization' => 'AI-Powered Categorization',
                'ai_categorization_desc' => 'When category or priority is not selected, our AI will automatically analyze the ticket content and suggest the most appropriate values.',
                'ai_suggested_category_confidence' => 'AI suggested category with :percent% confidence',
                'ticket_number_title' => 'Ticket #:number',
                'customer_name' => 'Customer Name',
                'customer_email' => 'Customer Email',
                'very_poor' => 'Very Poor',
                'poor' => 'Poor',
                'okay' => 'Okay',
                'good' => 'Good',
                'excellent' => 'Excellent',
                'system' => 'System',
                'notification_permission_help' => 'Please enable notifications in your browser settings for this site.',
                'desktop_notifications_enabled_title' => 'Desktop Notifications Enabled',
                'desktop_notifications_enabled_body' => 'You will now receive ticket notifications even when the browser is minimized.',
                'just_now' => 'Just now',
                'minutes_ago_short' => ':countm ago',
                'hours_ago_short' => ':counth ago',
                'days_ago_short' => ':countd ago',
                'web' => 'Web',
                'api' => 'API',
            ],
            'km' => [
                'app_support_desk' => 'ប្រព័ន្ធជំនួយ',
                'app_support_portal' => 'ផតថលជំនួយ',
                'language' => 'ភាសា',
                'english' => 'អង់គ្លេស',
                'khmer' => 'ខ្មែរ',
                'dashboard' => 'ផ្ទាំងគ្រប់គ្រង',
                'tickets' => 'សំណើ',
                'my_tickets' => 'សំណើរបស់ខ្ញុំ',
                'all_tickets' => 'សំណើទាំងអស់',
                'new_ticket' => 'សំណើថ្មី',
                'create_ticket' => 'បង្កើតសំណើ',
                'knowledge_base' => 'មូលដ្ឋានចំណេះដឹង',
                'analytics' => 'វិភាគ',
                'settings' => 'ការកំណត់',
                'general' => 'ទូទៅ',
                'categories' => 'ប្រភេទ',
                'users' => 'អ្នកប្រើប្រាស់',
                'email' => 'អ៊ីមែល',
                'telegram' => 'Telegram',
                'canned_responses' => 'ចម្លើយរួចស្រេច',
                'sla_configuration' => 'ការកំណត់ SLA',
                'notifications' => 'ការជូនដំណឹង',
                'mark_all_read' => 'សម្គាល់ថាបានអានទាំងអស់',
                'desktop_notifications' => 'ការជូនដំណឹងលើផ្ទៃតុ',
                'enabled' => 'បានបើក',
                'blocked' => 'បានបិទ',
                'not_set' => 'មិនទាន់កំណត់',
                'enable_desktop_notifications' => 'បើកការជូនដំណឹងលើផ្ទៃតុ',
                'no_notifications' => 'មិនមានការជូនដំណឹង',
                'logout' => 'ចាកចេញ',
                'login' => 'ចូលគណនី',
                'register' => 'ចុះឈ្មោះ',
                'welcome_back' => 'សូមស្វាគមន៍មកវិញ',
                'email_address' => 'អាសយដ្ឋានអ៊ីមែល',
                'password' => 'ពាក្យសម្ងាត់',
                'sign_in' => 'ចូល',
                'dont_have_account' => 'មិនទាន់មានគណនីមែនទេ?',
                'create_one' => 'បង្កើតគណនី',
                'create_your_account' => 'បង្កើតគណនីរបស់អ្នក',
                'company_name' => 'ឈ្មោះក្រុមហ៊ុន',
                'your_name' => 'ឈ្មោះរបស់អ្នក',
                'confirm_password' => 'បញ្ជាក់ពាក្យសម្ងាត់',
                'create_account' => 'បង្កើតគណនី',
                'already_have_account' => 'មានគណនីរួចហើយ?',
                'sign_in_link' => 'ចូលគណនី',
                'modern_ai_ticketing_system' => 'ប្រព័ន្ធគ្រប់គ្រងសំណើឆ្លាតវៃដោយ AI',
                'all_rights_reserved' => 'រក្សាសិទ្ធិគ្រប់យ៉ាង។',
                'all' => 'ទាំងអស់',
                'my_profile' => 'ប្រវត្តិរូបរបស់ខ្ញុំ',
                'open_tickets' => 'សំណើបើក',
                'urgent' => 'បន្ទាន់',
                'in_progress' => 'កំពុងដំណើរការ',
                'pending' => 'រង់ចាំ',
                'active' => 'កំពុងសកម្ម',
                'resolved_today' => 'ដោះស្រាយថ្ងៃនេះ',
                'unassigned' => 'មិនទាន់ចាត់តាំង',
                'sla_breach_alert' => 'ការជូនដំណឹងរំលោភ SLA',
                'ticket_requires_attention' => 'មានសំណើចំនួន :count ត្រូវការចាប់អារម្មណ៍ភ្លាម (ស្តង់ដារ ITIL)',
                'view_analytics' => 'មើលវិភាគ',
                'response_sla_breached' => 'បានរំលោភ SLA ការឆ្លើយតប',
                'resolution_sla_breached' => 'បានរំលោភ SLA ការដោះស្រាយ',
                'sla_breach_in_minutes' => 'នឹងរំលោភ SLA ក្នុង :minutes នាទី',
                'more_tickets_near_sla' => '+ នៅសល់ :count សំណើ ជិតរំលោភ SLA',
                'response_on_time' => 'ឆ្លើយតបទាន់ពេល',
                'resolution_on_time' => 'ដោះស្រាយទាន់ពេល',
                'response_overdue' => 'ឆ្លើយតបហួសពេល',
                'resolution_overdue' => 'ដោះស្រាយហួសពេល',
                'needs_immediate_response' => 'ត្រូវការឆ្លើយតបភ្លាម',
                'needs_immediate_resolution' => 'ត្រូវការដោះស្រាយភ្លាម',
                'breached' => 'បានរំលោភ',
                'recent_tickets' => 'សំណើថ្មីៗ',
                'view_all' => 'មើលទាំងអស់',
                'no_tickets_yet' => 'មិនទាន់មានសំណើ',
                'by_category' => 'តាមប្រភេទ',
                'open' => 'បើក',
                'recent_activity' => 'សកម្មភាពថ្មីៗ',
                'total_tickets' => 'សំណើសរុប :count',
                'filter' => 'តម្រង',
                'clear' => 'សម្អាត',
                'search_tickets' => 'ស្វែងរកសំណើ...',
                'all_status' => 'ស្ថានភាពទាំងអស់',
                'all_priority' => 'អាទិភាពទាំងអស់',
                'all_categories' => 'ប្រភេទទាំងអស់',
                'all_agents' => 'ភ្នាក់ងារទាំងអស់',
                'no_tickets_found' => 'រកមិនឃើញសំណើ',
                'try_adjusting_filters' => 'សាកល្បងប្ដូរតម្រង ឬបង្កើតសំណើថ្មី។',
                'source' => 'ប្រភព',
                'page_of' => 'ទំព័រ :current នៃ :total',
                'previous' => 'មុន',
                'next' => 'បន្ទាប់',
                'submit_support_request' => 'ផ្ញើសំណើសុំជំនួយ',
                'describe_issue_support' => 'សូមពិពណ៌នាបញ្ហា ហើយយើងនឹងឆ្លើយតបឱ្យបានឆាប់បំផុត។',
                'subject' => 'ប្រធានបទ',
                'description' => 'ពិពណ៌នា',
                'category' => 'ប្រភេទ',
                'select_category_optional' => 'ជ្រើសរើសប្រភេទ (មិនបាច់ក៏បាន)',
                'we_categorize_for_you' => 'បើមិនប្រាកដទេ យើងនឹងចាត់ប្រភេទឱ្យអ្នក។',
                'brief_summary_issue' => 'សង្ខេបខ្លីអំពីបញ្ហារបស់អ្នក',
                'provide_detail_issue' => 'សូមផ្តល់ព័ត៌មានលម្អិតអំពីបញ្ហា...',
                'include_steps_errors' => 'រួមបញ្ចូលជំហានធ្វើឡើងវិញ កំហុស និងរូបភាពប្រសិនបើមាន។',
                'cancel' => 'បោះបង់',
                'submit_ticket' => 'ផ្ញើសំណើ',
                'create_new_ticket' => 'បង្កើតសំណើថ្មី',
                'fill_ticket_details' => 'បំពេញព័ត៌មានខាងក្រោមដើម្បីបង្កើតសំណើជំនួយ',
                'create_ticket_help_team' => 'បង្កើតសំណើថ្មីដើម្បីទទួលបានជំនួយពីក្រុមគាំទ្ររបស់យើង។',
                'created_on' => 'បានបង្កើតនៅ',
                'conversation' => 'ការសន្ទនា',
                'support_team' => 'ក្រុមគាំទ្រ',
                'support' => 'គាំទ្រ',
                'attachments' => 'ឯកសារភ្ជាប់',
                'add_reply' => 'បន្ថែមការឆ្លើយតប',
                'reply' => 'ឆ្លើយតប',
                'type_your_message' => 'វាយសាររបស់អ្នក...',
                'attachments_optional' => 'ឯកសារភ្ជាប់ (ជាជម្រើស)',
                'click_to_upload' => 'ចុចដើម្បីអាប់ឡូដ',
                'or_drag_drop' => 'ឬ អូសទម្លាក់',
                'images_docs_limit' => 'រូបភាព PDF ឯកសារ អតិបរមា 10MB មួយឯកសារ',
                'send_reply' => 'ផ្ញើការឆ្លើយតប',
                'internal_note' => 'កំណត់ចំណាំផ្ទៃក្នុង',
                'ticket_closed_notice' => 'សំណើនេះត្រូវបានបិទ។ ប្រសិនបើត្រូវការជំនួយបន្ថែម សូមបង្កើតសំណើថ្មី។',
                'profile_settings' => 'ការកំណត់ប្រវត្តិរូប',
                'update_account_info' => 'កែប្រែព័ត៌មានគណនី',
                'full_name' => 'ឈ្មោះពេញ',
                'email_cannot_change' => 'មិនអាចប្តូរអ៊ីមែលបានទេ',
                'phone_number' => 'លេខទូរស័ព្ទ',
                'change_password' => 'ប្តូរពាក្យសម្ងាត់',
                'leave_blank_keep_password' => 'ទុកទទេដើម្បីរក្សាពាក្យសម្ងាត់ចាស់',
                'current_password' => 'ពាក្យសម្ងាត់បច្ចុប្បន្ន',
                'new_password' => 'ពាក្យសម្ងាត់ថ្មី',
                'save_changes' => 'រក្សាទុកការផ្លាស់ប្តូរ',
                'telegram_connected' => 'បានភ្ជាប់ Telegram',
                'account_linked_telegram' => 'គណនីរបស់អ្នកបានភ្ជាប់ជាមួយ Telegram',
                'connect_telegram' => 'ភ្ជាប់ Telegram',
                'link_telegram_for_tickets' => 'ភ្ជាប់ Telegram ដើម្បីបង្កើត និងគ្រប់គ្រងសំណើតាមការជជែក។ សូមទាក់ទងក្រុមគាំទ្រសម្រាប់ bot link។',
                'properties' => 'លក្ខណៈសម្បត្តិ',
                'assign_to' => 'ចាត់តាំងទៅ',
                'uncategorized' => 'មិនទាន់មានប្រភេទ',
                'requester' => 'អ្នកស្នើ',
                'customer_satisfaction' => 'ការពេញចិត្តរបស់អតិថិជន',
                'customer_feedback' => 'មតិយោបល់អតិថិជន',
                'rated_on' => 'បានវាយតម្លៃនៅ',
                'survey_sent_awaiting' => 'បានផ្ញើស្ទង់មតិ កំពុងរង់ចាំការឆ្លើយតប',
                'sent_on' => 'បានផ្ញើនៅ',
                'activity' => 'សកម្មភាព',
                'quick_responses' => 'ចម្លើយរហ័ស',
                'select_canned_response' => 'ជ្រើសរើសចម្លើយរួចស្រេច...',
                'internal_note_hidden' => 'កំណត់ចំណាំផ្ទៃក្នុង (លាក់ពីអតិថិជន)',
                'add_note' => 'បន្ថែមកំណត់ចំណាំ',
                'auto_detect_ai' => 'រកឃើញស្វ័យប្រវត្តិ (AI)',
                'leave_empty_ai_category' => 'ទុកទទេដើម្បីឱ្យ AI ចាត់ប្រភេទ',
                'priority' => 'អាទិភាព',
                'low' => 'ទាប',
                'medium' => 'មធ្យម',
                'high' => 'ខ្ពស់',
                'resolved' => 'បានដោះស្រាយ',
                'closed' => 'បិទ',
                'status' => 'ស្ថានភាព',
                'requester_info' => 'អ្នកស្នើ',
                'ai_powered_categorization' => 'ការចាត់ប្រភេទដោយ AI',
                'ai_categorization_desc' => 'នៅពេលមិនជ្រើសប្រភេទ ឬអាទិភាព AI នឹងវិភាគមាតិកាសំណើ ហើយផ្តល់តម្លៃសមរម្យបំផុត។',
                'ai_suggested_category_confidence' => 'AI បានណែនាំប្រភេទដោយមានភាពជឿជាក់ :percent%',
                'ticket_number_title' => 'សំណើលេខ #:number',
                'customer_name' => 'ឈ្មោះអតិថិជន',
                'customer_email' => 'អ៊ីមែលអតិថិជន',
                'very_poor' => 'អន់ណាស់',
                'poor' => 'អន់',
                'okay' => 'មធ្យម',
                'good' => 'ល្អ',
                'excellent' => 'ល្អបំផុត',
                'system' => 'ប្រព័ន្ធ',
                'notification_permission_help' => 'សូមបើកការជូនដំណឹងក្នុងការកំណត់របស់កម្មវិធីរុករកសម្រាប់គេហទំព័រនេះ។',
                'desktop_notifications_enabled_title' => 'បានបើកការជូនដំណឹងលើផ្ទៃតុ',
                'desktop_notifications_enabled_body' => 'អ្នកនឹងទទួលបានការជូនដំណឹងសំណើ ទោះបីជាបង្អួចកម្មវិធីរុករកត្រូវបានបង្រួមក៏ដោយ។',
                'just_now' => 'មុននេះបន្តិច',
                'minutes_ago_short' => ':countនាទីមុន',
                'hours_ago_short' => ':countម៉ោងមុន',
                'days_ago_short' => ':countថ្ងៃមុន',
                'web' => 'វេប',
                'api' => 'API',
            ],
        ];

        $messages['en'] = array_merge($messages['en'], [
            'success' => 'Success',
            'validation_failed' => 'Validation failed',
            'please_fix_errors' => 'Please fix the errors',
            'please_fix_errors_below' => 'Please fix the errors below',
            'please_fix_validation_errors' => 'Please fix the validation errors',
            'unauthorized' => 'Unauthorized',
            'forbidden' => 'Forbidden',
            'an_error_occurred_try_again_later' => 'An error occurred. Please try again later.',
            'file_not_found' => 'File not found',
            'invalid_request' => 'Invalid request',
            'invalid_role' => 'Invalid role',
            'invalid_email_format' => 'Invalid email format',
            'invalid_email_address' => 'Invalid email address',
            'email_already_exists' => 'Email already exists',
            'name_required' => 'Name is required',
            'email_required' => 'Email is required',
            'password_required' => 'Password is required',
            'password_min_chars' => 'Password must be at least :min characters',
            'passwords_do_not_match' => 'Passwords do not match',
            'company_name_required' => 'Company name is required',
            'title_required_min_chars' => 'Title is required (minimum :min characters)',
            'content_required_min_chars' => 'Content is required (minimum :min characters)',
            'title_and_content_required' => 'Title and content are required',
            'subject_and_description_required' => 'Subject and description are required',
            'message_or_attachment_required' => 'Message or attachment is required',
            'ticket_not_found' => 'Ticket not found',
            'file_upload_failed' => 'File upload failed: :error',
            'reply_sent_success' => 'Reply sent successfully',
            'your_reply_sent' => 'Your reply has been sent',
            'current_password_required_to_change' => 'Current password is required to change password',
            'current_password_incorrect' => 'Current password is incorrect',
            'profile_updated_success' => 'Profile updated successfully',
            'customer_ticket_submitted' => 'Your ticket :ticket has been submitted. We\'ll get back to you soon!',
            'auth_email_password_required' => 'Email and password are required',
            'auth_invalid_email_or_password' => 'Invalid email or password',
            'auth_invalid_credentials' => 'Invalid credentials',
            'auth_account_disabled' => 'Account is disabled',
            'auth_login_successful' => 'Login successful',
            'auth_account_created_welcome' => 'Account created successfully! Welcome to Support Desk.',
            'category_name_required' => 'Category name is required',
            'category_created_success' => 'Category created successfully',
            'category_updated_success' => 'Category updated successfully',
            'category_deleted_success' => 'Category deleted successfully',
            'category_not_found' => 'Category not found',
            'article_not_found' => 'Article not found',
            'article_published_success' => 'Article published successfully',
            'article_updated_success' => 'Article updated successfully',
            'article_deleted_success' => 'Article deleted successfully',
            'settings_updated_success' => 'Settings updated successfully',
            'email_settings_updated_success' => 'Email settings updated successfully',
            'telegram_settings_updated_success' => 'Telegram settings updated successfully',
            'user_created_success' => 'User created successfully',
            'user_updated_success' => 'User updated successfully',
            'user_deleted_success' => 'User deleted successfully',
            'user_not_found' => 'User not found',
            'cannot_remove_last_admin' => 'Cannot remove the last admin',
            'cannot_delete_last_admin' => 'Cannot delete the last admin',
            'cannot_delete_own_account' => 'You cannot delete your own account',
            'canned_response_created_success' => 'Canned response created successfully',
            'canned_response_updated' => 'Canned response updated',
            'canned_response_deleted' => 'Canned response deleted',
            'canned_response_not_found' => 'Canned response not found',
            'response_time_min_1' => 'Response time must be at least 1 minute',
            'resolution_time_min_1' => 'Resolution time must be at least 1 minute',
            'resolution_time_gt_response_time' => 'Resolution time must be greater than response time',
            'sla_policy_updated_success' => 'SLA policy updated successfully',
            'unsupported_format' => 'Unsupported format',
            'telegram_not_configured' => 'Telegram not configured',
            'webhook_configured_successfully' => 'Webhook configured successfully',
            'push_invalid_subscription_data' => 'Invalid subscription data',
            'push_subscription_successful' => 'Push subscription successful',
            'push_unsubscription_successful' => 'Push unsubscription successful',
            'push_not_configured' => 'Push notifications not configured',
            'push_test_notification_sent' => 'Test notification sent - check your browser/desktop!',
            'push_test_notification_failed' => 'Failed to send notification',
            'validation_required' => ':field is required',
            'validation_email' => ':field must be a valid email address',
            'validation_min' => ':field must be at least :min characters',
            'validation_max' => ':field must not exceed :max characters',
            'validation_numeric' => ':field must be a number',
            'validation_in' => ':field must be one of: :values',
            'validation_confirmed' => ':field confirmation does not match',
            'field_name' => 'Name',
            'field_email' => 'Email',
            'field_password' => 'Password',
            'field_password_confirmation' => 'Password confirmation',
            'field_company_name' => 'Company name',
            'field_subject' => 'Subject',
            'field_description' => 'Description',
            'field_requester_email' => 'Requester email',
            'field_requester_name' => 'Requester name',
            'field_title' => 'Title',
            'field_content' => 'Content',
            'field_role' => 'Role',
            'field_response_time_minutes' => 'Response time',
            'field_resolution_time_minutes' => 'Resolution time',
            'field_current_password' => 'Current password',
            'field_new_password' => 'New password',
            'field_message' => 'Message',
            'field_category_name' => 'Category name',
            'subject_required' => 'Subject is required',
            'description_required' => 'Description is required',
            'requester_email_required' => 'Requester email is required',
            'requester_name_required' => 'Requester name is required',
            'status_invalid' => 'Invalid status',
            'priority_invalid' => 'Invalid priority',
            'attachment_placeholder' => '[Attachment]',
            'ticket_created_success' => 'Ticket created successfully',
            'ticket_created_success_with_number' => 'Ticket :ticket created successfully',
            'ticket_status_updated_success' => 'Ticket status updated successfully',
            'ticket_assignment_updated_success' => 'Ticket assignment updated successfully',
            'ticket_priority_updated_success' => 'Ticket priority updated successfully',
            'ticket_category_updated_success' => 'Ticket category updated successfully',
        ]);

        $messages['km'] = array_merge($messages['km'], [
            'success' => 'ជោគជ័យ',
            'validation_failed' => 'ការផ្ទៀងផ្ទាត់បរាជ័យ',
            'please_fix_errors' => 'សូមកែតម្រូវកំហុស',
            'please_fix_errors_below' => 'សូមកែតម្រូវកំហុសខាងក្រោម',
            'please_fix_validation_errors' => 'សូមកែតម្រូវកំហុសការផ្ទៀងផ្ទាត់',
            'unauthorized' => 'មិនមានសិទ្ធិ',
            'forbidden' => 'ហាមឃាត់',
            'an_error_occurred_try_again_later' => 'មានបញ្ហាកើតឡើង។ សូមព្យាយាមម្តងទៀត។',
            'file_not_found' => 'រកមិនឃើញឯកសារ',
            'invalid_request' => 'សំណើមិនត្រឹមត្រូវ',
            'invalid_role' => 'តួនាទីមិនត្រឹមត្រូវ',
            'invalid_email_format' => 'ទម្រង់អ៊ីមែលមិនត្រឹមត្រូវ',
            'invalid_email_address' => 'អាសយដ្ឋានអ៊ីមែលមិនត្រឹមត្រូវ',
            'email_already_exists' => 'អ៊ីមែលនេះមានរួចហើយ',
            'name_required' => 'ត្រូវការឈ្មោះ',
            'email_required' => 'ត្រូវការអ៊ីមែល',
            'password_required' => 'ត្រូវការពាក្យសម្ងាត់',
            'password_min_chars' => 'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច :min តួអក្សរ',
            'passwords_do_not_match' => 'ពាក្យសម្ងាត់មិនដូចគ្នា',
            'company_name_required' => 'ត្រូវការឈ្មោះក្រុមហ៊ុន',
            'title_required_min_chars' => 'ត្រូវការចំណងជើង (យ៉ាងតិច :min តួអក្សរ)',
            'content_required_min_chars' => 'ត្រូវការមាតិកា (យ៉ាងតិច :min តួអក្សរ)',
            'title_and_content_required' => 'ត្រូវការចំណងជើង និង មាតិកា',
            'subject_and_description_required' => 'ត្រូវការប្រធានបទ និង ការពិពណ៌នា',
            'message_or_attachment_required' => 'ត្រូវការសារ ឬ ឯកសារភ្ជាប់',
            'ticket_not_found' => 'រកមិនឃើញសំណើ',
            'file_upload_failed' => 'ការផ្ទុកឯកសារបរាជ័យ: :error',
            'reply_sent_success' => 'បានផ្ញើការឆ្លើយតបដោយជោគជ័យ',
            'your_reply_sent' => 'ការឆ្លើយតបរបស់អ្នកត្រូវបានផ្ញើរួចរាល់',
            'current_password_required_to_change' => 'ត្រូវការពាក្យសម្ងាត់បច្ចុប្បន្នដើម្បីប្ដូរ',
            'current_password_incorrect' => 'ពាក្យសម្ងាត់បច្ចុប្បន្នមិនត្រឹមត្រូវ',
            'profile_updated_success' => 'បានធ្វើបច្ចុប្បន្នភាពប្រវត្តិរូបដោយជោគជ័យ',
            'customer_ticket_submitted' => 'សំណើ :ticket របស់អ្នកត្រូវបានផ្ញើរួចរាល់។ យើងនឹងឆ្លើយតបឱ្យបានឆាប់។',
            'auth_email_password_required' => 'ត្រូវការអ៊ីមែល និង ពាក្យសម្ងាត់',
            'auth_invalid_email_or_password' => 'អ៊ីមែល ឬ ពាក្យសម្ងាត់មិនត្រឹមត្រូវ',
            'auth_invalid_credentials' => 'ព័ត៌មានចូលប្រើមិនត្រឹមត្រូវ',
            'auth_account_disabled' => 'គណនីត្រូវបានបិទ',
            'auth_login_successful' => 'ចូលប្រើដោយជោគជ័យ',
            'auth_account_created_welcome' => 'បានបង្កើតគណនីដោយជោគជ័យ! សូមស្វាគមន៍មកកាន់ Support Desk។',
            'category_name_required' => 'ត្រូវការឈ្មោះប្រភេទ',
            'category_created_success' => 'បានបង្កើតប្រភេទដោយជោគជ័យ',
            'category_updated_success' => 'បានធ្វើបច្ចុប្បន្នភាពប្រភេទដោយជោគជ័យ',
            'category_deleted_success' => 'បានលុបប្រភេទដោយជោគជ័យ',
            'category_not_found' => 'រកមិនឃើញប្រភេទ',
            'article_not_found' => 'រកមិនឃើញអត្ថបទ',
            'article_published_success' => 'បានបោះពុម្ពអត្ថបទដោយជោគជ័យ',
            'article_updated_success' => 'បានធ្វើបច្ចុប្បន្នភាពអត្ថបទដោយជោគជ័យ',
            'article_deleted_success' => 'បានលុបអត្ថបទដោយជោគជ័យ',
            'settings_updated_success' => 'បានធ្វើបច្ចុប្បន្នភាពការកំណត់ដោយជោគជ័យ',
            'email_settings_updated_success' => 'បានធ្វើបច្ចុប្បន្នភាពការកំណត់អ៊ីមែលដោយជោគជ័យ',
            'telegram_settings_updated_success' => 'បានធ្វើបច្ចុប្បន្នភាពការកំណត់ Telegram ដោយជោគជ័យ',
            'user_created_success' => 'បានបង្កើតអ្នកប្រើដោយជោគជ័យ',
            'user_updated_success' => 'បានធ្វើបច្ចុប្បន្នភាពអ្នកប្រើដោយជោគជ័យ',
            'user_deleted_success' => 'បានលុបអ្នកប្រើដោយជោគជ័យ',
            'user_not_found' => 'រកមិនឃើញអ្នកប្រើ',
            'cannot_remove_last_admin' => 'មិនអាចដក admin ចុងក្រោយបានទេ',
            'cannot_delete_last_admin' => 'មិនអាចលុប admin ចុងក្រោយបានទេ',
            'cannot_delete_own_account' => 'អ្នកមិនអាចលុបគណនីរបស់ខ្លួនឯងបានទេ',
            'canned_response_created_success' => 'បានបង្កើតចម្លើយរួចស្រេចដោយជោគជ័យ',
            'canned_response_updated' => 'បានធ្វើបច្ចុប្បន្នភាពចម្លើយរួចស្រេច',
            'canned_response_deleted' => 'បានលុបចម្លើយរួចស្រេច',
            'canned_response_not_found' => 'រកមិនឃើញចម្លើយរួចស្រេច',
            'response_time_min_1' => 'ពេលវេលាឆ្លើយតបត្រូវមានយ៉ាងតិច 1 នាទី',
            'resolution_time_min_1' => 'ពេលវេលាដោះស្រាយត្រូវមានយ៉ាងតិច 1 នាទី',
            'resolution_time_gt_response_time' => 'ពេលវេលាដោះស្រាយត្រូវធំជាងពេលវេលាឆ្លើយតប',
            'sla_policy_updated_success' => 'បានធ្វើបច្ចុប្បន្នភាពគោលការណ៍ SLA ដោយជោគជ័យ',
            'unsupported_format' => 'ទម្រង់មិនត្រូវបានគាំទ្រ',
            'telegram_not_configured' => 'មិនទាន់កំណត់ Telegram',
            'webhook_configured_successfully' => 'បានកំណត់ webhook ដោយជោគជ័យ',
            'push_invalid_subscription_data' => 'ទិន្នន័យ subscription មិនត្រឹមត្រូវ',
            'push_subscription_successful' => 'បាន subscribe push ដោយជោគជ័យ',
            'push_unsubscription_successful' => 'បាន unsubscribe push ដោយជោគជ័យ',
            'push_not_configured' => 'មិនទាន់កំណត់ push notifications',
            'push_test_notification_sent' => 'បានផ្ញើការជូនដំណឹងសាកល្បងហើយ សូមពិនិត្យ browser/desktop របស់អ្នក',
            'push_test_notification_failed' => 'ផ្ញើការជូនដំណឹងមិនបាន',
            'validation_required' => ':field ត្រូវបានទាមទារ',
            'validation_email' => ':field ត្រូវតែជាអ៊ីមែលត្រឹមត្រូវ',
            'validation_min' => ':field ត្រូវមានយ៉ាងតិច :min តួអក្សរ',
            'validation_max' => ':field មិនត្រូវលើស :max តួអក្សរ',
            'validation_numeric' => ':field ត្រូវតែជាលេខ',
            'validation_in' => ':field ត្រូវតែជាមួយក្នុងចំណោម: :values',
            'validation_confirmed' => 'ការបញ្ជាក់ :field មិនត្រូវគ្នា',
            'field_name' => 'ឈ្មោះ',
            'field_email' => 'អ៊ីមែល',
            'field_password' => 'ពាក្យសម្ងាត់',
            'field_password_confirmation' => 'បញ្ជាក់ពាក្យសម្ងាត់',
            'field_company_name' => 'ឈ្មោះក្រុមហ៊ុន',
            'field_subject' => 'ប្រធានបទ',
            'field_description' => 'ការពិពណ៌នា',
            'field_requester_email' => 'អ៊ីមែលអ្នកស្នើ',
            'field_requester_name' => 'ឈ្មោះអ្នកស្នើ',
            'field_title' => 'ចំណងជើង',
            'field_content' => 'មាតិកា',
            'field_role' => 'តួនាទី',
            'field_response_time_minutes' => 'ពេលវេលាឆ្លើយតប',
            'field_resolution_time_minutes' => 'ពេលវេលាដោះស្រាយ',
            'field_current_password' => 'ពាក្យសម្ងាត់បច្ចុប្បន្ន',
            'field_new_password' => 'ពាក្យសម្ងាត់ថ្មី',
            'field_message' => 'សារ',
            'field_category_name' => 'ឈ្មោះប្រភេទ',
            'subject_required' => 'ត្រូវការប្រធានបទ',
            'description_required' => 'ត្រូវការការពិពណ៌នា',
            'requester_email_required' => 'ត្រូវការអ៊ីមែលអ្នកស្នើ',
            'requester_name_required' => 'ត្រូវការឈ្មោះអ្នកស្នើ',
            'status_invalid' => 'ស្ថានភាពមិនត្រឹមត្រូវ',
            'priority_invalid' => 'អាទិភាពមិនត្រឹមត្រូវ',
            'attachment_placeholder' => '[ឯកសារភ្ជាប់]',
            'ticket_created_success' => 'បានបង្កើតសំណើដោយជោគជ័យ',
            'ticket_created_success_with_number' => 'បានបង្កើតសំណើ :ticket ដោយជោគជ័យ',
            'ticket_status_updated_success' => 'បានធ្វើបច្ចុប្បន្នភាពស្ថានភាពសំណើដោយជោគជ័យ',
            'ticket_assignment_updated_success' => 'បានធ្វើបច្ចុប្បន្នភាពការចាត់តាំងសំណើដោយជោគជ័យ',
            'ticket_priority_updated_success' => 'បានធ្វើបច្ចុប្បន្នភាពអាទិភាពសំណើដោយជោគជ័យ',
            'ticket_category_updated_success' => 'បានធ្វើបច្ចុប្បន្នភាពប្រភេទសំណើដោយជោគជ័យ',
        ]);

        
        // AUTO_VIEW_TRANSLATIONS_START
        $messages['en'] = array_merge($messages['en'], [
            'v_1_hour' => '1 hour',
            'v_24_7' => '24/7',
            'v_24_hours' => '24 hours',
            'v_4_hours' => '4 hours',
            'v_72_hours_3_days' => '72 hours (3 days)',
            'v_8_am_5_30_pm' => '8 AM - 5:30 PM',
            'v_8_hours' => '8 hours',
            'v_actions' => 'Actions',
            'v_active' => 'Active',
            'v_add_canned_response' => 'Add Canned Response',
            'v_add_category' => 'Add Category',
            'v_add_new_category' => 'Add New Category',
            'v_add_new_user' => 'Add New User',
            'v_add_response' => 'Add Response',
            'v_admin' => 'Admin',
            'v_agent' => 'Agent',
            'v_agent_assigned_tickets_only' => 'Agent (Assigned tickets only)',
            'v_agent_performance' => 'Agent Performance',
            'v_ai_keywords' => 'AI Keywords',
            'v_alert_group_chat_id_optional' => 'Alert Group Chat ID (optional)',
            'v_all_categories' => 'All Categories',
            'v_all_categories_2' => 'All categories',
            'v_allow_customers_to_create_tickets_via_telegram' => 'Allow customers to create tickets via Telegram',
            'v_analytics_reports' => 'Analytics & Reports',
            'v_are_you_sure_you_want_to_delete_this_article' => 'Are you sure you want to delete this article?',
            'v_article_info' => 'Article Info',
            'v_articles_you_ve_written' => 'Articles you\'ve written',
            'v_assigned_ticket_alerts' => 'Assigned Ticket Alerts',
            'v_author' => 'Author',
            'v_auto' => 'Auto',
            'v_auto_assign_to' => 'Auto-assign to',
            'v_automatically_create_tickets_from_incoming_emails' => 'Automatically create tickets from incoming emails',
            'v_average_response_resolution_time_minutes' => 'Average Response & Resolution Time (minutes)',
            'v_avg_resolution' => 'Avg Resolution',
            'v_avg_resolution_time' => 'Avg Resolution Time',
            'v_avg_response' => 'Avg Response',
            'v_avg_response_time' => 'Avg Response Time',
            'v_back' => 'Back',
            'v_back_office' => 'Back Office',
            'v_back_office_agent' => 'Back Office Agent',
            'v_back_to_articles' => 'Back to Articles',
            'v_based_on_itil_iso_20000_international_standards' => 'Based on ITIL & ISO 20000 International Standards',
            'v_be_the_first_to_share_knowledge' => 'Be the first to share knowledge!',
            'v_bot_token' => 'Bot Token',
            'v_bot_username' => 'Bot Username',
            'v_brief_description' => 'Brief description',
            'v_business_hours_8_am_5_30_pm' => 'Business Hours (8 AM - 5:30 PM)',
            'v_business_hours_only' => 'Business Hours Only',
            'v_cancel' => 'Cancel',
            'v_canned_responses' => 'Canned Responses',
            'v_categories' => 'Categories',
            'v_category' => 'Category',
            'v_category_name' => 'Category name',
            'v_check_ticket_status' => 'Check ticket status',
            'v_color' => 'Color',
            'v_comma_separated_keywords_for_ai_categorization' => 'Comma-separated keywords for AI categorization',
            'v_company_name' => 'Company Name',
            'v_company_settings' => 'Company Settings',
            'v_configure_imap_smtp_for_automatic_ticket_creation_from_email' => 'Configure IMAP/SMTP for automatic ticket creation from emails',
            'v_configure_service_level_agreement_times_for_each_priority_le' => 'Configure Service Level Agreement times for each priority level based on ITIL international standards.',
            'v_connect_a_telegram_bot_to_receive_and_manage_support_tickets' => 'Connect a Telegram bot to receive and manage support tickets',
            'v_content' => 'Content',
            'v_copied' => 'Copied',
            'v_copy_full_text' => 'Copy full text',
            'v_create_a_new_support_ticket' => 'Create a new support ticket',
            'v_create_pre_written_responses_for_common_questions' => 'Create pre-written responses for common questions',
            'v_created' => 'Created',
            'v_cron_job_setup' => 'CRON Job Setup',
            'v_customer' => 'Customer',
            'v_customer_satisfaction' => 'Customer Satisfaction',
            'v_days' => 'days',
            'v_delete' => 'Delete',
            'v_delete_this_category' => 'Delete this category?',
            'v_delete_this_response' => 'Delete this response?',
            'v_delete_this_user' => 'Delete this user?',
            'v_description' => 'Description',
            'v_draft' => 'Draft',
            'v_edit' => 'Edit',
            'v_edit_article' => 'Edit Article',
            'v_edit_article_knowledge_base' => 'Edit Article - Knowledge Base',
            'v_email' => 'Email',
            'v_email_address' => 'Email Address',
            'v_email_configuration' => 'Email Configuration',
            'v_email_integration' => 'Email Integration',
            'v_email_settings' => 'Email Settings',
            'v_enable_ai_auto_categorization' => 'Enable AI auto-categorization',
            'v_enable_auto_assignment_based_on_category' => 'Enable auto-assignment based on category',
            'v_enable_customer_self_service_portal' => 'Enable customer self-service portal',
            'v_encryption' => 'Encryption',
            'v_enter_article_title' => 'Enter article title...',
            'v_example_tkt_000001' => 'Example: TKT-000001',
            'v_export_csv' => 'Export CSV',
            'v_failed_to_delete_article' => 'Failed to delete article',
            'v_featured' => 'Featured',
            'v_featured_article' => 'Featured article',
            'v_featured_articles' => 'Featured Articles',
            'v_find_answers_and_share_knowledge' => 'Find answers and share knowledge',
            'v_from_email' => 'From Email',
            'v_from_name' => 'From Name',
            'v_front_back_office_assigned_tickets_only' => 'Front/Back Office (Assigned tickets only)',
            'v_front_office' => 'Front Office',
            'v_front_office_agent' => 'Front Office Agent',
            'v_full_name' => 'Full Name',
            'v_general_settings' => 'General Settings',
            'v_get_your_bot_token_from' => 'Get your bot token from',
            'v_high' => 'High',
            'v_high_priority' => 'High Priority',
            'v_hours' => 'hours',
            'v_hours_average' => 'hours average',
            'v_if_set_alerts_are_also_sent_to_this_group_chat' => 'If set, alerts are also sent to this group chat',
            'v_imap_host' => 'IMAP Host',
            'v_imap_password' => 'IMAP Password',
            'v_imap_port' => 'IMAP Port',
            'v_imap_username' => 'IMAP Username',
            'v_inactive' => 'Inactive',
            'v_incoming_mail_imap' => 'Incoming Mail (IMAP)',
            'v_iso_20000_kpi' => 'ISO 20000 KPI',
            'v_itil_standard' => 'ITIL Standard',
            'v_itil_standard_reference' => 'ITIL Standard Reference',
            'v_keyword1_keyword2_keyword3' => 'keyword1, keyword2, keyword3',
            'v_keywords' => 'Keywords',
            'v_knowledge_base' => 'Knowledge Base',
            'v_last_30_days' => 'Last 30 Days',
            'v_last_7_days' => 'Last 7 Days',
            'v_last_90_days' => 'Last 90 Days',
            'v_last_login' => 'Last Login',
            'v_leave_blank_to_keep_current_password' => 'Leave blank to keep current password',
            'v_link_email_account_to_telegram' => 'Link email account to Telegram',
            'v_low' => 'Low',
            'v_low_priority' => 'Low Priority',
            'v_manage_your_company_information_and_preferences' => 'Manage your company information and preferences',
            'v_medium' => 'Medium',
            'v_medium_priority' => 'Medium Priority',
            'v_min' => 'min',
            'v_my_articles' => 'My Articles',
            'v_my_articles_knowledge_base' => 'My Articles - Knowledge Base',
            'v_n_a' => 'N/A',
            'v_name' => 'Name',
            'v_never' => 'Never',
            'v_new_article' => 'New Article',
            'v_new_password' => 'New password',
            'v_no_articles_found' => 'No articles found',
            'v_no_articles_yet' => 'No articles yet',
            'v_no_auto_assignment' => 'No auto-assignment',
            'v_no_canned_responses_yet_add_one_above' => 'No canned responses yet. Add one above.',
            'v_no_categories_yet_add_one_above' => 'No categories yet. Add one above.',
            'v_none' => 'None',
            'v_note' => 'Note:',
            'v_nothing_to_copy' => 'Nothing to copy',
            'v_notify_assigned_agents_when_a_ticket_is_assigned_or_a_custom' => 'Notify assigned agents when a ticket is assigned or a customer replies',
            'v_of' => 'of',
            'v_open_this_url_in_your_browser_replace_your_bot_token' => 'Open this URL in your browser (replace YOUR_BOT_TOKEN):',
            'v_open_tickets' => 'open tickets',
            'v_outgoing_mail_smtp' => 'Outgoing Mail (SMTP)',
            'v_page' => 'Page',
            'v_password' => 'Password',
            'v_phone' => 'Phone',
            'v_please_enter_article_content' => 'Please enter article content',
            'v_popular' => 'Popular',
            'v_priority' => 'Priority',
            'v_publish_article' => 'Publish Article',
            'v_publish_immediately' => 'Publish immediately',
            'v_published' => 'Published',
            'v_quick_access_code_e_g_thanks' => 'Quick access code (e.g., #thanks)',
            'v_rating' => 'Rating',
            'v_recommended_resolution_times' => 'Recommended Resolution Times',
            'v_recommended_response_times' => 'Recommended Response Times',
            'v_related_articles' => 'Related Articles',
            'v_reset_password' => 'Reset Password',
            'v_resolution_rate' => 'Resolution Rate',
            'v_resolution_sla' => 'Resolution SLA',
            'v_resolution_time' => 'Resolution Time',
            'v_resolution_time_minutes' => 'Resolution Time (minutes)',
            'v_resolved' => 'resolved',
            'v_resolved_2' => 'Resolved',
            'v_response_sla' => 'Response SLA',
            'v_response_time' => 'Response Time',
            'v_response_time_minutes' => 'Response Time (minutes)',
            'v_response_title' => 'Response title',
            'v_role' => 'Role',
            'v_role_types' => 'Role Types:',
            'v_save' => 'Save',
            'v_save_changes' => 'Save Changes',
            'v_save_email_settings' => 'Save Email Settings',
            'v_save_settings' => 'Save Settings',
            'v_save_telegram_settings' => 'Save Telegram Settings',
            'v_save_your_bot_settings_above' => 'Save your bot settings above',
            'v_saved_responses' => 'Saved Responses',
            'v_search' => 'Search',
            'v_search_articles' => 'Search articles...',
            'v_select_a_category_optional' => 'Select a category (optional)',
            'v_sender_information' => 'Sender Information',
            'v_share_your_knowledge_with_the_team' => 'Share your knowledge with the team',
            'v_shortcut' => 'Shortcut',
            'v_show_help_message' => 'Show help message',
            'v_sla_compliance' => 'SLA Compliance',
            'v_sla_compliance_trend' => 'SLA Compliance Trend (%)',
            'v_sla_configuration' => 'SLA Configuration',
            'v_sla_configuration_itil_standard' => 'SLA Configuration (ITIL Standard)',
            'v_sla_policies_by_priority' => 'SLA Policies by Priority',
            'v_sla_success' => 'SLA Success',
            'v_smtp_host' => 'SMTP Host',
            'v_smtp_password' => 'SMTP Password',
            'v_smtp_port' => 'SMTP Port',
            'v_smtp_username' => 'SMTP Username',
            'v_start_the_bot_and_see_welcome_message' => 'Start the bot and see welcome message',
            'v_start_writing_and_share_your_knowledge' => 'Start writing and share your knowledge!',
            'v_status' => 'Status',
            'v_support_email' => 'Support Email',
            'v_support_team' => 'Support Team',
            'v_tag1_tag2_tag3_comma_separated' => 'tag1, tag2, tag3 (comma separated)',
            'v_tags' => 'Tags',
            'v_team_members' => 'Team Members',
            'v_telegram_bot_configuration' => 'Telegram Bot Configuration',
            'v_telegram_integration' => 'Telegram Integration',
            'v_telegram_settings' => 'Telegram Settings',
            'v_this_message_is_shown_when_users_start_the_bot' => 'This message is shown when users start the bot',
            'v_this_runs_every_5_minutes_to_check_for_new_emails' => 'This runs every 5 minutes to check for new emails.',
            'v_ticket_number_prefix' => 'Ticket Number Prefix',
            'v_ticket_settings' => 'Ticket Settings',
            'v_ticket_volume_trend' => 'Ticket Volume Trend',
            'v_tickets' => 'Tickets',
            'v_tickets_by_category' => 'Tickets by Category',
            'v_times' => 'times',
            'v_times_are_in_minutes_standard_business_hours_are_8_am_5_30_p' => 'Times are in minutes. Standard business hours are 8 AM - 5:30 PM, Monday - Friday.',
            'v_timezone' => 'Timezone',
            'v_title' => 'Title',
            'v_to_process_incoming_emails_automatically_set_up_a_cron_job' => 'To process incoming emails automatically, set up a CRON job:',
            'v_to_set_up_the_webhook' => 'To set up the webhook:',
            'v_total_tickets' => 'Total Tickets',
            'v_type_your_canned_response' => 'Type your canned response...',
            'v_uncategorized' => 'Uncategorized',
            'v_update_article' => 'Update Article',
            'v_update_your_article' => 'Update your article',
            'v_updated' => 'Updated',
            'v_urgent' => 'Urgent',
            'v_urgent_critical' => 'Urgent (Critical)',
            'v_use_the_toolbar_to_format_your_content' => 'Use the toolbar to format your content.',
            'v_used' => 'Used',
            'v_user' => 'User',
            'v_users' => 'Users',
            'v_view_my_articles' => 'View my articles',
            'v_view_your_open_tickets' => 'View your open tickets',
            'v_views' => 'views',
            'v_views_2' => 'Views',
            'v_webhook_configuration' => 'Webhook Configuration',
            'v_webhook_url' => 'Webhook URL',
            'v_welcome_message' => 'Welcome Message',
            'v_welcome_to_our_support_bot_how_can_we_help_you_today' => 'Welcome to our Support Bot! How can we help you today?',
            'v_write_an_article' => 'Write an Article',
            'v_write_article' => 'Write Article',
            'v_write_article_knowledge_base' => 'Write Article - Knowledge Base',
            'v_write_your_article_content_here' => 'Write your article content here...',
            'v_write_your_first_article' => 'Write Your First Article',
            'v_you_should_see_a_success_message' => 'You should see a success message',
        ]);

        $messages['km'] = array_merge($messages['km'], [
            'v_1_hour' => '1 ម៉ោង',
            'v_24_7' => '24/7',
            'v_24_hours' => '24 ម៉ោង',
            'v_4_hours' => '4 ម៉ោង',
            'v_72_hours_3_days' => '72 ម៉ោង (3 ថ្ងៃ)',
            'v_8_am_5_30_pm' => '8 ព្រឹក - 5:30 ល្ងាច',
            'v_8_hours' => '8 ម៉ោង',
            'v_actions' => 'សកម្មភាព',
            'v_active' => 'សកម្ម',
            'v_add_canned_response' => 'បន្ថែមចម្លើយរួចស្រេច',
            'v_add_category' => 'បន្ថែមប្រភេទ',
            'v_add_new_category' => 'បន្ថែមប្រភេទថ្មី',
            'v_add_new_user' => 'បន្ថែមអ្នកប្រើថ្មី',
            'v_add_response' => 'បន្ថែមចម្លើយ',
            'v_admin' => 'អ្នកគ្រប់គ្រង',
            'v_agent' => 'ភ្នាក់ងារ',
            'v_agent_assigned_tickets_only' => 'ភ្នាក់ងារ (តែសំណើដែលបានចាត់តាំង)',
            'v_agent_performance' => 'ប្រសិទ្ធភាពភ្នាក់ងារ',
            'v_ai_keywords' => 'ពាក្យគន្លឹះ AI',
            'v_alert_group_chat_id_optional' => 'Alert Group Chat ID (ជាជម្រើស)',
            'v_all_categories' => 'ប្រភេទទាំងអស់',
            'v_all_categories_2' => 'ប្រភេទទាំងអស់',
            'v_allow_customers_to_create_tickets_via_telegram' => 'អនុញ្ញាតឱ្យអតិថិជនបង្កើតសំណើតាម Telegram',
            'v_analytics_reports' => 'វិភាគ និងរបាយការណ៍',
            'v_are_you_sure_you_want_to_delete_this_article' => 'តើអ្នកប្រាកដថាចង់លុបអត្ថបទនេះឬ?',
            'v_article_info' => 'ព័ត៌មានអត្ថបទ',
            'v_articles_you_ve_written' => 'អត្ថបទដែលអ្នកបានសរសេរ',
            'v_assigned_ticket_alerts' => 'ការជូនដំណឹងសំណើដែលបានចាត់តាំង',
            'v_author' => 'អ្នកនិពន្ធ',
            'v_auto' => 'ស្វ័យប្រវត្តិ',
            'v_auto_assign_to' => 'ចាត់តាំងស្វ័យប្រវត្តិទៅ',
            'v_automatically_create_tickets_from_incoming_emails' => 'បង្កើតសំណើស្វ័យប្រវត្តិពីអ៊ីមែលចូល',
            'v_average_response_resolution_time_minutes' => 'ពេលឆ្លើយតប និងដោះស្រាយមធ្យម (នាទី)',
            'v_avg_resolution' => 'ដោះស្រាយមធ្យម',
            'v_avg_resolution_time' => 'ពេលដោះស្រាយមធ្យម',
            'v_avg_response' => 'ឆ្លើយតបមធ្យម',
            'v_avg_response_time' => 'ពេលឆ្លើយតបមធ្យម',
            'v_back' => 'ត្រឡប់ក្រោយ',
            'v_back_office' => 'Back Office',
            'v_back_office_agent' => 'ភ្នាក់ងារ Back Office',
            'v_back_to_articles' => 'ត្រឡប់ទៅអត្ថបទ',
            'v_based_on_itil_iso_20000_international_standards' => 'ផ្អែកលើស្តង់ដារអន្តរជាតិ ITIL និង ISO 20000',
            'v_be_the_first_to_share_knowledge' => 'ចាប់ផ្តើមចែករំលែកចំណេះដឹងមុនគេ!',
            'v_bot_token' => 'Bot Token',
            'v_bot_username' => 'ឈ្មោះអ្នកប្រើ Bot',
            'v_brief_description' => 'ការពិពណ៌នាខ្លី',
            'v_business_hours_8_am_5_30_pm' => 'ម៉ោងធ្វើការ (8 ព្រឹក - 5:30 ល្ងាច)',
            'v_business_hours_only' => 'តែក្នុងម៉ោងធ្វើការ',
            'v_cancel' => 'បោះបង់',
            'v_canned_responses' => 'ចម្លើយរួចស្រេច',
            'v_categories' => 'ប្រភេទ',
            'v_category' => 'ប្រភេទ',
            'v_category_name' => 'ឈ្មោះប្រភេទ',
            'v_check_ticket_status' => 'ពិនិត្យស្ថានភាពសំណើ',
            'v_color' => 'ពណ៌',
            'v_comma_separated_keywords_for_ai_categorization' => 'ពាក្យគន្លឹះបំបែកដោយសញ្ញាក្បៀសសម្រាប់ AI ចាត់ប្រភេទ',
            'v_company_name' => 'ឈ្មោះក្រុមហ៊ុន',
            'v_company_settings' => 'ការកំណត់ក្រុមហ៊ុន',
            'v_configure_imap_smtp_for_automatic_ticket_creation_from_email' => 'កំណត់ IMAP/SMTP សម្រាប់បង្កើតសំណើស្វ័យប្រវត្តិពីអ៊ីមែល',
            'v_configure_service_level_agreement_times_for_each_priority_le' => 'កំណត់ពេលវេលា Service Level Agreement សម្រាប់អាទិភាពនីមួយៗ ដោយផ្អែកលើស្តង់ដារ ITIL អន្តរជាតិ។',
            'v_connect_a_telegram_bot_to_receive_and_manage_support_tickets' => 'ភ្ជាប់ bot Telegram ដើម្បីទទួល និងគ្រប់គ្រងសំណើជំនួយ',
            'v_content' => 'ខ្លឹមសារ',
            'v_copied' => 'បានចម្លង',
            'v_copy_full_text' => 'ចម្លងអត្ថបទពេញ',
            'v_create_a_new_support_ticket' => 'បង្កើតសំណើជំនួយថ្មី',
            'v_create_pre_written_responses_for_common_questions' => 'បង្កើតចម្លើយដែលសរសេររួចសម្រាប់សំណួរញឹកញាប់',
            'v_created' => 'បានបង្កើត',
            'v_cron_job_setup' => 'ការរៀបចំ CRON Job',
            'v_customer' => 'អតិថិជន',
            'v_customer_satisfaction' => 'ការពេញចិត្តអតិថិជន',
            'v_days' => 'ថ្ងៃ',
            'v_delete' => 'លុប',
            'v_delete_this_category' => 'លុបប្រភេទនេះឬ?',
            'v_delete_this_response' => 'លុបចម្លើយនេះឬ?',
            'v_delete_this_user' => 'លុបអ្នកប្រើនេះឬ?',
            'v_description' => 'ការពិពណ៌នា',
            'v_draft' => 'ព្រាង',
            'v_edit' => 'កែសម្រួល',
            'v_edit_article' => 'កែសម្រួលអត្ថបទ',
            'v_edit_article_knowledge_base' => 'កែសម្រួលអត្ថបទ - មូលដ្ឋានចំណេះដឹង',
            'v_email' => 'អ៊ីមែល',
            'v_email_address' => 'អាសយដ្ឋានអ៊ីមែល',
            'v_email_configuration' => 'ការកំណត់អ៊ីមែល',
            'v_email_integration' => 'ការភ្ជាប់អ៊ីមែល',
            'v_email_settings' => 'ការកំណត់អ៊ីមែល',
            'v_enable_ai_auto_categorization' => 'បើក AI ចាត់ប្រភេទស្វ័យប្រវត្តិ',
            'v_enable_auto_assignment_based_on_category' => 'បើកការចាត់តាំងស្វ័យប្រវត្តិតាមប្រភេទ',
            'v_enable_customer_self_service_portal' => 'បើកផតថលសេវាខ្លួនឯងសម្រាប់អតិថិជន',
            'v_encryption' => 'ការអ៊ិនគ្រីប',
            'v_enter_article_title' => 'បញ្ចូលចំណងជើងអត្ថបទ...',
            'v_example_tkt_000001' => 'ឧទាហរណ៍៖ TKT-000001',
            'v_export_csv' => 'នាំចេញ CSV',
            'v_failed_to_delete_article' => 'បរាជ័យក្នុងការលុបអត្ថបទ',
            'v_featured' => 'លេចធ្លោ',
            'v_featured_article' => 'អត្ថបទលេចធ្លោ',
            'v_featured_articles' => 'អត្ថបទលេចធ្លោ',
            'v_find_answers_and_share_knowledge' => 'ស្វែងរកចម្លើយ និងចែករំលែកចំណេះដឹង',
            'v_from_email' => 'អ៊ីមែលអ្នកផ្ញើ',
            'v_from_name' => 'ឈ្មោះអ្នកផ្ញើ',
            'v_front_back_office_assigned_tickets_only' => 'Front/Back Office (តែសំណើដែលបានចាត់តាំង)',
            'v_front_office' => 'Front Office',
            'v_front_office_agent' => 'ភ្នាក់ងារ Front Office',
            'v_full_name' => 'ឈ្មោះពេញ',
            'v_general_settings' => 'ការកំណត់ទូទៅ',
            'v_get_your_bot_token_from' => 'ទទួលបាន bot token របស់អ្នកពី',
            'v_high' => 'ខ្ពស់',
            'v_high_priority' => 'អាទិភាពខ្ពស់',
            'v_hours' => 'ម៉ោង',
            'v_hours_average' => 'ម៉ោងជាមធ្យម',
            'v_if_set_alerts_are_also_sent_to_this_group_chat' => 'បើកំណត់ នឹងផ្ញើការជូនដំណឹងទៅក្រុម chat នេះផងដែរ',
            'v_imap_host' => 'IMAP Host',
            'v_imap_password' => 'IMAP Password',
            'v_imap_port' => 'IMAP Port',
            'v_imap_username' => 'IMAP Username',
            'v_inactive' => 'មិនសកម្ម',
            'v_incoming_mail_imap' => 'អ៊ីមែលចូល (IMAP)',
            'v_iso_20000_kpi' => 'សូចនាករ ISO 20000',
            'v_itil_standard' => 'ស្តង់ដារ ITIL',
            'v_itil_standard_reference' => 'ឯកសារយោងស្តង់ដារ ITIL',
            'v_keyword1_keyword2_keyword3' => 'ពាក្យ1, ពាក្យ2, ពាក្យ3',
            'v_keywords' => 'ពាក្យគន្លឹះ',
            'v_knowledge_base' => 'មូលដ្ឋានចំណេះដឹង',
            'v_last_30_days' => '៣០ ថ្ងៃចុងក្រោយ',
            'v_last_7_days' => '៧ ថ្ងៃចុងក្រោយ',
            'v_last_90_days' => '៩០ ថ្ងៃចុងក្រោយ',
            'v_last_login' => 'ចូលប្រើចុងក្រោយ',
            'v_leave_blank_to_keep_current_password' => 'ទុកទទេដើម្បីរក្សាពាក្យសម្ងាត់បច្ចុប្បន្ន',
            'v_link_email_account_to_telegram' => 'ភ្ជាប់គណនីអ៊ីមែលទៅ Telegram',
            'v_low' => 'ទាប',
            'v_low_priority' => 'អាទិភាពទាប',
            'v_manage_your_company_information_and_preferences' => 'គ្រប់គ្រងព័ត៌មាន និងចំណូលចិត្តរបស់ក្រុមហ៊ុន',
            'v_medium' => 'មធ្យម',
            'v_medium_priority' => 'អាទិភាពមធ្យម',
            'v_min' => 'នាទី',
            'v_my_articles' => 'អត្ថបទរបស់ខ្ញុំ',
            'v_my_articles_knowledge_base' => 'អត្ថបទរបស់ខ្ញុំ - មូលដ្ឋានចំណេះដឹង',
            'v_n_a' => 'មិនមាន',
            'v_name' => 'ឈ្មោះ',
            'v_never' => 'មិនធ្លាប់',
            'v_new_article' => 'អត្ថបទថ្មី',
            'v_new_password' => 'ពាក្យសម្ងាត់ថ្មី',
            'v_no_articles_found' => 'មិនមានអត្ថបទ',
            'v_no_articles_yet' => 'មិនទាន់មានអត្ថបទ',
            'v_no_auto_assignment' => 'មិនចាត់តាំងស្វ័យប្រវត្តិ',
            'v_no_canned_responses_yet_add_one_above' => 'មិនទាន់មានចម្លើយរួចស្រេចទេ។ សូមបន្ថែមខាងលើ។',
            'v_no_categories_yet_add_one_above' => 'មិនទាន់មានប្រភេទទេ។ សូមបន្ថែមខាងលើ។',
            'v_none' => 'គ្មាន',
            'v_note' => 'ចំណាំ៖',
            'v_nothing_to_copy' => 'មិនមានអត្ថបទសម្រាប់ចម្លង',
            'v_notify_assigned_agents_when_a_ticket_is_assigned_or_a_custom' => 'ជូនដំណឹងភ្នាក់ងារដែលបានចាត់តាំង ពេលសំណើត្រូវបានចាត់តាំង ឬអតិថិជនឆ្លើយតប',
            'v_of' => 'នៃ',
            'v_open_this_url_in_your_browser_replace_your_bot_token' => 'បើក URL នេះក្នុង browser (ប្ដូរ YOUR_BOT_TOKEN):',
            'v_open_tickets' => 'សំណើកំពុងបើក',
            'v_outgoing_mail_smtp' => 'អ៊ីមែលចេញ (SMTP)',
            'v_page' => 'ទំព័រ',
            'v_password' => 'ពាក្យសម្ងាត់',
            'v_phone' => 'ទូរស័ព្ទ',
            'v_please_enter_article_content' => 'សូមបញ្ចូលខ្លឹមសារអត្ថបទ',
            'v_popular' => 'ពេញនិយម',
            'v_priority' => 'អាទិភាព',
            'v_publish_article' => 'បោះពុម្ពអត្ថបទ',
            'v_publish_immediately' => 'បោះពុម្ពភ្លាមៗ',
            'v_published' => 'បានបោះពុម្ព',
            'v_quick_access_code_e_g_thanks' => 'កូដចូលប្រើលឿន (ឧ. #thanks)',
            'v_rating' => 'ពិន្ទុ',
            'v_recommended_resolution_times' => 'ពេលដោះស្រាយដែលណែនាំ',
            'v_recommended_response_times' => 'ពេលឆ្លើយតបដែលណែនាំ',
            'v_related_articles' => 'អត្ថបទពាក់ព័ន្ធ',
            'v_reset_password' => 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
            'v_resolution_rate' => 'អត្រាដោះស្រាយ',
            'v_resolution_sla' => 'SLA ការដោះស្រាយ',
            'v_resolution_time' => 'ពេលដោះស្រាយ',
            'v_resolution_time_minutes' => 'ពេលដោះស្រាយ (នាទី)',
            'v_resolved' => 'បានដោះស្រាយ',
            'v_resolved_2' => 'បានដោះស្រាយ',
            'v_response_sla' => 'SLA ការឆ្លើយតប',
            'v_response_time' => 'ពេលឆ្លើយតប',
            'v_response_time_minutes' => 'ពេលឆ្លើយតប (នាទី)',
            'v_response_title' => 'ចំណងជើងចម្លើយ',
            'v_role' => 'តួនាទី',
            'v_role_types' => 'ប្រភេទតួនាទី៖',
            'v_save' => 'រក្សាទុក',
            'v_save_changes' => 'រក្សាទុកការកែប្រែ',
            'v_save_email_settings' => 'រក្សាទុកការកំណត់អ៊ីមែល',
            'v_save_settings' => 'រក្សាទុកការកំណត់',
            'v_save_telegram_settings' => 'រក្សាទុកការកំណត់ Telegram',
            'v_save_your_bot_settings_above' => 'រក្សាទុកការកំណត់ bot ខាងលើ',
            'v_saved_responses' => 'ចម្លើយដែលបានរក្សាទុក',
            'v_search' => 'ស្វែងរក',
            'v_search_articles' => 'ស្វែងរកអត្ថបទ...',
            'v_select_a_category_optional' => 'ជ្រើសរើសប្រភេទ (មិនបាច់ក៏បាន)',
            'v_sender_information' => 'ព័ត៌មានអ្នកផ្ញើ',
            'v_share_your_knowledge_with_the_team' => 'ចែករំលែកចំណេះដឹងរបស់អ្នកជាមួយក្រុម',
            'v_shortcut' => 'ផ្លូវកាត់',
            'v_show_help_message' => 'បង្ហាញសារជំនួយ',
            'v_sla_compliance' => 'អនុលោម SLA',
            'v_sla_compliance_trend' => 'និន្នាការអនុលោម SLA (%)',
            'v_sla_configuration' => 'ការកំណត់ SLA',
            'v_sla_configuration_itil_standard' => 'ការកំណត់ SLA (ស្តង់ដារ ITIL)',
            'v_sla_policies_by_priority' => 'គោលការណ៍ SLA តាមអាទិភាព',
            'v_sla_success' => 'ជោគជ័យ SLA',
            'v_smtp_host' => 'SMTP Host',
            'v_smtp_password' => 'SMTP Password',
            'v_smtp_port' => 'SMTP Port',
            'v_smtp_username' => 'SMTP Username',
            'v_start_the_bot_and_see_welcome_message' => 'ចាប់ផ្តើម bot និងមើលសារស្វាគមន៍',
            'v_start_writing_and_share_your_knowledge' => 'ចាប់ផ្តើមសរសេរ និងចែករំលែកចំណេះដឹងរបស់អ្នក!',
            'v_status' => 'ស្ថានភាព',
            'v_support_email' => 'អ៊ីមែលជំនួយ',
            'v_support_team' => 'ក្រុមគាំទ្រ',
            'v_tag1_tag2_tag3_comma_separated' => 'ស្លាក1, ស្លាក2, ស្លាក3 (បំបែកដោយសញ្ញាក្បៀស)',
            'v_tags' => 'ស្លាក',
            'v_team_members' => 'សមាជិកក្រុម',
            'v_telegram_bot_configuration' => 'ការកំណត់ Bot Telegram',
            'v_telegram_integration' => 'ការភ្ជាប់ Telegram',
            'v_telegram_settings' => 'ការកំណត់ Telegram',
            'v_this_message_is_shown_when_users_start_the_bot' => 'សារនេះនឹងបង្ហាញពេលអ្នកប្រើចាប់ផ្តើម bot',
            'v_this_runs_every_5_minutes_to_check_for_new_emails' => 'វាដំណើរការរៀងរាល់ ៥ នាទីម្តង ដើម្បីពិនិត្យអ៊ីមែលថ្មី។',
            'v_ticket_number_prefix' => 'បុព្វបទលេខសំណើ',
            'v_ticket_settings' => 'ការកំណត់សំណើ',
            'v_ticket_volume_trend' => 'និន្នាការបរិមាណសំណើ',
            'v_tickets' => 'សំណើ',
            'v_tickets_by_category' => 'សំណើតាមប្រភេទ',
            'v_times' => 'ដង',
            'v_times_are_in_minutes_standard_business_hours_are_8_am_5_30_p' => 'ពេលវេលាគិតជា នាទី។ ម៉ោងធ្វើការស្តង់ដារ 8 ព្រឹក - 5:30 ល្ងាច ច័ន្ទ - សុក្រ។',
            'v_timezone' => 'តំបន់ម៉ោង',
            'v_title' => 'ចំណងជើង',
            'v_to_process_incoming_emails_automatically_set_up_a_cron_job' => 'ដើម្បីដំណើរការអ៊ីមែលចូលស្វ័យប្រវត្តិ សូមកំណត់ CRON job:',
            'v_to_set_up_the_webhook' => 'ដើម្បីកំណត់ webhook:',
            'v_total_tickets' => 'សំណើសរុប',
            'v_type_your_canned_response' => 'វាយចម្លើយរួចស្រេចរបស់អ្នក...',
            'v_uncategorized' => 'មិនទាន់មានប្រភេទ',
            'v_update_article' => 'ធ្វើបច្ចុប្បន្នភាពអត្ថបទ',
            'v_update_your_article' => 'ធ្វើបច្ចុប្បន្នភាពអត្ថបទរបស់អ្នក',
            'v_updated' => 'បានកែប្រែ',
            'v_urgent' => 'បន្ទាន់',
            'v_urgent_critical' => 'បន្ទាន់ (សំខាន់ខ្លាំង)',
            'v_use_the_toolbar_to_format_your_content' => 'ប្រើ toolbar ដើម្បីរៀបចំទម្រង់ខ្លឹមសារ។',
            'v_used' => 'បានប្រើ',
            'v_user' => 'អ្នកប្រើ',
            'v_users' => 'អ្នកប្រើប្រាស់',
            'v_view_my_articles' => 'មើលអត្ថបទរបស់ខ្ញុំ',
            'v_view_your_open_tickets' => 'មើលសំណើបើករបស់អ្នក',
            'v_views' => 'ដងមើល',
            'v_views_2' => 'ចំនួនមើល',
            'v_webhook_configuration' => 'ការកំណត់ Webhook',
            'v_webhook_url' => 'Webhook URL',
            'v_welcome_message' => 'សារស្វាគមន៍',
            'v_welcome_to_our_support_bot_how_can_we_help_you_today' => 'សូមស្វាគមន៍មកកាន់ Bot ជំនួយរបស់យើង! ថ្ងៃនេះយើងអាចជួយអ្វីបានខ្លះ?',
            'v_write_an_article' => 'សរសេរអត្ថបទ',
            'v_write_article' => 'សរសេរអត្ថបទ',
            'v_write_article_knowledge_base' => 'សរសេរអត្ថបទ - មូលដ្ឋានចំណេះដឹង',
            'v_write_your_article_content_here' => 'សរសេរខ្លឹមសារអត្ថបទរបស់អ្នកនៅទីនេះ...',
            'v_write_your_first_article' => 'សរសេរអត្ថបទដំបូងរបស់អ្នក',
            'v_you_should_see_a_success_message' => 'អ្នកគួរតែឃើញសារជោគជ័យ',
        ]);
        // AUTO_VIEW_TRANSLATIONS_END

        $messages['en'] = array_merge($messages['en'], [
            'delete' => 'Delete',
            'error_404_back' => 'Go Back',
            'error_404_heading' => 'Page Not Found',
            'error_404_message' => 'The page you are looking for does not exist.',
            'error_404_title' => '404 - Page Not Found',
            'login_email_placeholder' => 'your@email.com',
            'login_password_placeholder' => 'Enter your password',
            'users_add_department' => 'Add Department',
            'users_all_departments' => 'All Departments',
            'users_all_roles' => 'All Roles',
            'users_all_status' => 'All Status',
            'users_bot_username' => 'Bot username',
            'users_connected' => 'Connected',
            'users_deactivate_department_confirm' => 'Deactivate this department?',
            'users_department_created_successfully' => 'Department created successfully',
            'users_department_feature_unavailable' => 'Department feature is unavailable. Run department migrations first.',
            'users_department_label' => 'Department',
            'users_department_name_label' => 'Department Name',
            'users_department_name_placeholder' => 'Enter department name',
            'users_department_name_required' => 'Department name is required.',
            'users_department_not_found' => 'Department not found.',
            'users_department_optional' => 'Department (optional)',
            'users_department_removed_successfully' => 'Department removed successfully.',
            'users_department_tables_unavailable' => 'Department tables are unavailable. Run migrations first.',
            'users_departments_desc' => 'Create departments and assign managers.',
            'users_departments_title' => 'Departments',
            'users_enable_telegram_prefix' => 'Enable Telegram Link in',
            'users_enable_telegram_suffix' => 'to generate start links for staff.',
            'users_filter' => 'Filter',
            'users_invalid_department_manager_selected' => 'Selected department manager is invalid.',
            'users_invalid_department_selected' => 'Selected department is invalid',
            'users_link_telegram' => 'Link Telegram',
            'users_manager' => 'Manager',
            'users_manager_optional' => 'Manager (optional)',
            'users_members' => 'Members',
            'users_no_department' => 'No department',
            'users_no_departments' => 'No departments yet.',
            'users_no_manager' => 'No manager',
            'users_no_match' => 'No users match your current filters.',
            'users_not_linked' => 'Not linked',
            'users_open_link_start' => 'Open this bot and tap Start once to link account.',
            'users_remove' => 'Remove',
            'users_reset' => 'Reset',
            'users_search_placeholder' => 'Search by name, email, role, or department',
            'users_showing_count' => 'Showing :filtered of :total users',
            'users_super_admin' => 'Super Admin',
            'users_tab_departments' => 'Departments',
            'users_tab_manage' => 'Manage Users',
            'users_telegram' => 'Telegram',
            'users_telegram_linking_desc' => 'Link staff accounts to Telegram for direct bot notifications.',
            'users_telegram_linking_title' => 'Telegram Account Linking',
            'users_unable_to_create_department' => 'Unable to create department.',
            'wf_assigned' => 'Assigned',
            'wf_auto_distribution_note' => 'Selected staff will receive incoming customer tickets using queue rules.',
            'wf_category_routing' => 'Category Routing',
            'wf_category_routing_matrix' => 'Category Routing Matrix',
            'wf_category_routing_matrix_desc' => 'Configure how each category is routed and assigned.',
            'wf_category_routing_rules' => 'Category Rules',
            'wf_configured_category_rules' => 'Configured Category Rules',
            'wf_configured_category_rules_desc' => 'One active rule per category.',
            'wf_console_desc' => 'Control routing, mappings, and staff hierarchy from one place.',
            'wf_console_title' => 'Workflow Hierarchy Console',
            'wf_current' => 'Current',
            'wf_current_step' => 'Current Step',
            'wf_customer_routing_hint' => 'Ticket is auto-routed based on category and workflow settings.',
            'wf_delete_category_routing_confirm' => 'Delete this category routing rule?',
            'wf_department_queue' => 'Department Queue',
            'wf_department_queue_help' => 'Route to a department and assign by queue strategy.',
            'wf_dept_manager' => 'Dept Manager',
            'wf_due_in' => 'Due in :time',
            'wf_hierarchy_nav' => 'Workflow Hierarchy',
            'wf_hierarchy_tree' => 'Hierarchy Tree',
            'wf_hierarchy_tree_caption' => 'Reporting structure based on staff-supervisor mapping.',
            'wf_incoming_customer_handlers' => 'Incoming Customer Handlers',
            'wf_incoming_customer_handlers_desc' => 'Choose staff allowed to receive incoming customer tickets.',
            'wf_incoming_handlers' => 'Incoming Handlers',
            'wf_mapped_staff_user' => 'Mapped Staff User',
            'wf_mappings' => 'Mappings',
            'wf_miniapp_staff_mapping' => 'Mini App Staff Mapping',
            'wf_miniapp_staff_mapping_desc' => 'Map Telegram Mini App staff profiles to internal users.',
            'wf_miniapp_staff_profiles' => 'Mini App Staff Profiles',
            'wf_mode' => 'Mode',
            'wf_next_escalation' => 'Next Escalation',
            'wf_next_step' => 'Next Step',
            'wf_no_active_staff_users' => 'No active staff users available.',
            'wf_no_category_routing_rules' => 'No category routing rules found.',
            'wf_no_due_time' => 'No due time',
            'wf_no_miniapp_staff_profiles' => 'No Mini App staff profiles found.',
            'wf_no_staff_reporting_data' => 'No staff reporting data available.',
            'wf_not_mapped' => 'Not mapped',
            'wf_other_linked_staff' => 'Other linked staff',
            'wf_overdue_by' => 'Overdue by :time',
            'wf_priority' => 'Priority',
            'wf_priority_help' => 'Category rule -> workflow/category auto-assign -> hierarchy fallback.',
            'wf_profile_count' => ':count profiles',
            'wf_queue_least_open' => 'Least Open',
            'wf_queue_round_robin' => 'Round Robin',
            'wf_queue_strategy' => 'Queue Strategy',
            'wf_route_department_queue' => 'Department Queue',
            'wf_route_staff_supervisor' => 'Staff -> Supervisor',
            'wf_route_use_default' => 'Use Workflow Default',
            'wf_routing_mode' => 'Routing Mode',
            'wf_rule_count' => ':count rules',
            'wf_save_incoming_handlers' => 'Save Incoming Handlers',
            'wf_save_rule' => 'Save Rule',
            'wf_select_category' => 'Select category',
            'wf_select_department' => 'Select department',
            'wf_settings_label' => 'Settings',
            'wf_staff_count' => ':count staff',
            'wf_staff_hierarchy' => 'Staff Hierarchy',
            'wf_staff_org_sitemap' => 'Staff Org Sitemap',
            'wf_staff_org_sitemap_desc' => 'Visual organization map for staff to supervisor links.',
            'wf_staff_supervisor_help' => 'For staff tickets, route to mapped supervisor/manager.',
            'wf_staff_to_supervisor' => 'Staff -> Supervisor',
            'wf_staff_under_who' => 'Staff Under Who',
            'wf_step_number' => 'Step #:step',
            'wf_step_of' => 'Step :current of :total',
            'wf_strategy' => 'Strategy',
            'wf_telegram_id' => 'Telegram ID',
            'wf_telegram_user_number' => 'Telegram user #:id',
            'wf_workflow' => 'Workflow',
            'wf_workflow_status' => 'Workflow Status',
            'wf_incoming_handlers_updated' => 'Incoming ticket handlers updated.',
            'wf_customer_owner_required' => 'Customer and owner are required.',
            'wf_selected_customer_invalid' => 'Selected customer is invalid.',
            'wf_selected_owner_must_staff' => 'Selected owner must be a staff user.',
            'wf_customer_owner_mapping_saved' => 'Customer owner mapping saved.',
            'wf_mapping_not_found' => 'Mapping not found.',
            'wf_customer_owner_mapping_deleted' => 'Customer owner mapping deleted.',
            'wf_user_supervisor_required' => 'User and supervisor are required.',
            'wf_user_supervisor_same_error' => 'User and supervisor cannot be the same.',
            'wf_selected_user_must_staff' => 'Selected user must be a staff user.',
            'wf_selected_supervisor_must_staff' => 'Selected supervisor must be a staff user.',
            'wf_user_reporting_mapping_saved' => 'User reporting mapping saved.',
            'wf_reporting_mapping_not_found' => 'Reporting mapping not found.',
            'wf_user_reporting_mapping_deleted' => 'User reporting mapping deleted.',
            'wf_miniapp_profile_required' => 'Mini App profile is required.',
            'wf_miniapp_staff_profile_invalid' => 'Selected Mini App staff profile is invalid.',
            'wf_mapped_user_must_active_staff' => 'Mapped user must be an active staff account.',
            'wf_miniapp_staff_mapping_saved' => 'Mini App staff mapping saved.',
            'wf_miniapp_staff_mapping_cleared' => 'Mini App staff mapping cleared.',
            'wf_category_required' => 'Category is required.',
            'wf_invalid_routing_mode' => 'Invalid routing mode.',
            'wf_invalid_queue_strategy' => 'Invalid queue strategy.',
            'wf_selected_category_invalid' => 'Selected category is invalid.',
            'wf_department_required_for_queue' => 'Department is required for department queue routing.',
            'wf_selected_department_invalid' => 'Selected department is invalid.',
            'wf_category_routing_table_unavailable' => 'Category routing table is not available. Run migrations first.',
            'wf_category_routing_saved' => 'Category routing rule saved.',
            'wf_category_routing_not_found' => 'Category routing rule not found.',
            'wf_category_routing_deleted' => 'Category routing rule deleted.',
            'wf_template_created' => 'Workflow template created.',
            'wf_template_not_found' => 'Workflow template not found.',
            'wf_template_updated' => 'Workflow template updated.',
            'wf_template_delete_active_blocked' => 'Cannot delete template with active workflow tickets.',
            'wf_template_deleted' => 'Workflow template deleted.',
            'wf_step_created' => 'Workflow step created.',
            'wf_step_create_failed' => 'Failed to create step. Check step order uniqueness and required fields.',
            'wf_step_not_found' => 'Workflow step not found.',
            'wf_step_updated' => 'Workflow step updated.',
            'wf_step_update_failed' => 'Failed to update step. Check step order uniqueness and required fields.',
            'wf_step_deleted' => 'Workflow step deleted.',
            'wf_template_name_required' => 'Template name is required.',
            'wf_invalid_trigger_source' => 'Invalid trigger source.',
            'wf_invalid_trigger_category' => 'Invalid trigger category.',
            'wf_workflow_template_required' => 'Workflow template is required.',
            'wf_selected_workflow_template_invalid' => 'Selected workflow template is invalid.',
            'wf_step_order_name_required' => 'Step order and name are required.',
            'wf_sla_minutes_min_1' => 'SLA minutes must be at least 1.',
            'wf_invalid_approver_type' => 'Invalid approver type.',
            'wf_approver_user_required' => 'Approver user is required for user approver type.',
            'wf_approver_role_required' => 'A valid role is required for role approver type.',
            'wf_department_required_for_approver' => 'Department is required for department manager approver type.',
        ]);

        $messages['km'] = array_merge($messages['km'], [
            'delete' => 'លុប',
            'error_404_back' => 'ត្រឡប់ក្រោយ',
            'error_404_heading' => 'រកមិនឃើញទំព័រ',
            'error_404_message' => 'ទំព័រដែលអ្នកកំពុងរកមិនមានទេ។',
            'error_404_title' => '404 - រកមិនឃើញទំព័រ',
            'login_email_placeholder' => 'your@email.com',
            'login_password_placeholder' => 'បញ្ចូលពាក្យសម្ងាត់',
            'users_add_department' => 'បន្ថែមផ្នែក',
            'users_all_departments' => 'គ្រប់ផ្នែក',
            'users_all_roles' => 'គ្រប់តួនាទី',
            'users_all_status' => 'គ្រប់ស្ថានភាព',
            'users_bot_username' => 'ឈ្មោះអ្នកប្រើ Bot',
            'users_connected' => 'បានភ្ជាប់',
            'users_deactivate_department_confirm' => 'បិទដំណើរការផ្នែកនេះមែនទេ?',
            'users_department_created_successfully' => 'បានបង្កើតផ្នែកដោយជោគជ័យ',
            'users_department_feature_unavailable' => 'មុខងារផ្នែកមិនទាន់មានទេ។ សូមរត់ migration ជាមុនសិន។',
            'users_department_label' => 'ផ្នែក',
            'users_department_name_label' => 'ឈ្មោះផ្នែក',
            'users_department_name_placeholder' => 'បញ្ចូលឈ្មោះផ្នែក',
            'users_department_name_required' => 'ត្រូវការឈ្មោះផ្នែក។',
            'users_department_not_found' => 'រកមិនឃើញផ្នែក។',
            'users_department_optional' => 'ផ្នែក (ជាជម្រើស)',
            'users_department_removed_successfully' => 'បានលុបផ្នែកដោយជោគជ័យ។',
            'users_department_tables_unavailable' => 'តារាងផ្នែកមិនទាន់មានទេ។ សូមរត់ migration ជាមុនសិន។',
            'users_departments_desc' => 'បង្កើតផ្នែក និងកំណត់អ្នកគ្រប់គ្រង។',
            'users_departments_title' => 'ផ្នែក',
            'users_enable_telegram_prefix' => 'សូមបើក Telegram Link ក្នុង',
            'users_enable_telegram_suffix' => 'ដើម្បីបង្កើត start link សម្រាប់បុគ្គលិក។',
            'users_filter' => 'តម្រង',
            'users_invalid_department_manager_selected' => 'អ្នកគ្រប់គ្រងផ្នែកដែលបានជ្រើសមិនត្រឹមត្រូវ។',
            'users_invalid_department_selected' => 'ផ្នែកដែលបានជ្រើសមិនត្រឹមត្រូវ',
            'users_link_telegram' => 'ភ្ជាប់ Telegram',
            'users_manager' => 'អ្នកគ្រប់គ្រង',
            'users_manager_optional' => 'អ្នកគ្រប់គ្រង (ជាជម្រើស)',
            'users_members' => 'សមាជិក',
            'users_no_department' => 'មិនមានផ្នែក',
            'users_no_departments' => 'មិនទាន់មានផ្នែកទេ។',
            'users_no_manager' => 'គ្មានអ្នកគ្រប់គ្រង',
            'users_no_match' => 'គ្មានអ្នកប្រើដែលត្រូវនឹងតម្រងបច្ចុប្បន្ន។',
            'users_not_linked' => 'មិនទាន់ភ្ជាប់',
            'users_open_link_start' => 'បើក bot នេះ ហើយចុច Start ម្តង ដើម្បីភ្ជាប់គណនី។',
            'users_remove' => 'លុប',
            'users_reset' => 'កំណត់ឡើងវិញ',
            'users_search_placeholder' => 'ស្វែងរកតាមឈ្មោះ អ៊ីមែល តួនាទី ឬផ្នែក',
            'users_showing_count' => 'បង្ហាញ :filtered នៃអ្នកប្រើសរុប :total',
            'users_super_admin' => 'Super Admin',
            'users_tab_departments' => 'ផ្នែក',
            'users_tab_manage' => 'គ្រប់គ្រងអ្នកប្រើ',
            'users_telegram' => 'Telegram',
            'users_telegram_linking_desc' => 'ភ្ជាប់គណនីបុគ្គលិកទៅ Telegram ដើម្បីទទួលការជូនដំណឹងពី bot។',
            'users_telegram_linking_title' => 'ការភ្ជាប់គណនី Telegram',
            'users_unable_to_create_department' => 'មិនអាចបង្កើតផ្នែកបានទេ។',
            'wf_assigned' => 'បានចាត់តាំង',
            'wf_auto_distribution_note' => 'បុគ្គលិកដែលបានជ្រើសនឹងទទួលសំណើអតិថិជនតាមច្បាប់ queue។',
            'wf_category_routing' => 'Routing តាមប្រភេទ',
            'wf_category_routing_matrix' => 'ម៉ាទ្រីស Routing តាមប្រភេទ',
            'wf_category_routing_matrix_desc' => 'កំណត់របៀបបញ្ជូន និងចាត់តាំងសម្រាប់ប្រភេទនីមួយៗ។',
            'wf_category_routing_rules' => 'ច្បាប់ Routing ប្រភេទ',
            'wf_configured_category_rules' => 'ច្បាប់ Routing ដែលបានកំណត់',
            'wf_configured_category_rules_desc' => 'ប្រភេទមួយ មានច្បាប់សកម្មមួយ។',
            'wf_console_desc' => 'គ្រប់គ្រង routing, mapping និង hierarchy បុគ្គលិកនៅកន្លែងតែមួយ។',
            'wf_console_title' => 'Workflow Hierarchy Console',
            'wf_current' => 'បច្ចុប្បន្ន',
            'wf_current_step' => 'ជំហានបច្ចុប្បន្ន',
            'wf_customer_routing_hint' => 'សំណើនឹងត្រូវបញ្ជូនស្វ័យប្រវត្តិតាមប្រភេទ និងការកំណត់ workflow។',
            'wf_delete_category_routing_confirm' => 'លុបច្បាប់ routing នេះមែនទេ?',
            'wf_department_queue' => 'Queue តាមផ្នែក',
            'wf_department_queue_help' => 'បញ្ជូនទៅផ្នែក ហើយចាត់តាំងតាមយុទ្ធសាស្រ្ត queue។',
            'wf_dept_manager' => 'អ្នកគ្រប់គ្រងផ្នែក',
            'wf_due_in' => 'ផុតកំណត់ក្នុង :time',
            'wf_hierarchy_nav' => 'Workflow Hierarchy',
            'wf_hierarchy_tree' => 'ដើមឈើ Hierarchy',
            'wf_hierarchy_tree_caption' => 'រចនាសម្ព័ន្ធរាយការណ៍ផ្អែកលើការផ្គូផ្គងបុគ្គលិក-អ្នកគ្រប់គ្រង។',
            'wf_incoming_customer_handlers' => 'អ្នកទទួលសំណើអតិថិជន',
            'wf_incoming_customer_handlers_desc' => 'ជ្រើសបុគ្គលិកដែលអនុញ្ញាតឱ្យទទួលសំណើអតិថិជនចូល។',
            'wf_incoming_handlers' => 'អ្នកទទួលសំណើចូល',
            'wf_mapped_staff_user' => 'អ្នកប្រើបុគ្គលិកដែលបានផ្គូផ្គង',
            'wf_mappings' => 'ការផ្គូផ្គង',
            'wf_miniapp_staff_mapping' => 'ការផ្គូផ្គងបុគ្គលិក Mini App',
            'wf_miniapp_staff_mapping_desc' => 'ផ្គូផ្គងប្រូហ្វាលបុគ្គលិក Telegram Mini App ទៅអ្នកប្រើក្នុងប្រព័ន្ធ។',
            'wf_miniapp_staff_profiles' => 'ប្រូហ្វាលបុគ្គលិក Mini App',
            'wf_mode' => 'របៀប',
            'wf_next_escalation' => 'ការបញ្ជូនបន្តបន្ទាប់',
            'wf_next_step' => 'ជំហានបន្ទាប់',
            'wf_no_active_staff_users' => 'មិនមានអ្នកប្រើបុគ្គលិកសកម្មទេ។',
            'wf_no_category_routing_rules' => 'មិនទាន់មានច្បាប់ routing តាមប្រភេទទេ។',
            'wf_no_due_time' => 'គ្មានពេលផុតកំណត់',
            'wf_no_miniapp_staff_profiles' => 'មិនទាន់មានប្រូហ្វាលបុគ្គលិក Mini App ទេ។',
            'wf_no_staff_reporting_data' => 'មិនមានទិន្នន័យរាយការណ៍បុគ្គលិកទេ។',
            'wf_not_mapped' => 'មិនទាន់ផ្គូផ្គង',
            'wf_other_linked_staff' => 'បុគ្គលិកដែលភ្ជាប់ផ្សេងទៀត',
            'wf_overdue_by' => 'ហួសពេល :time',
            'wf_priority' => 'អាទិភាព',
            'wf_priority_help' => 'ច្បាប់ប្រភេទ -> workflow/category auto-assign -> fallback hierarchy។',
            'wf_profile_count' => ':count ប្រូហ្វាល',
            'wf_queue_least_open' => 'Least Open',
            'wf_queue_round_robin' => 'Round Robin',
            'wf_queue_strategy' => 'យុទ្ធសាស្រ្ត Queue',
            'wf_route_department_queue' => 'Queue តាមផ្នែក',
            'wf_route_staff_supervisor' => 'បុគ្គលិក -> អ្នកគ្រប់គ្រង',
            'wf_route_use_default' => 'ប្រើ Workflow លំនាំដើម',
            'wf_routing_mode' => 'របៀប Routing',
            'wf_rule_count' => ':count ច្បាប់',
            'wf_save_incoming_handlers' => 'រក្សាទុកអ្នកទទួលសំណើចូល',
            'wf_save_rule' => 'រក្សាទុកច្បាប់',
            'wf_select_category' => 'ជ្រើសប្រភេទ',
            'wf_select_department' => 'ជ្រើសផ្នែក',
            'wf_settings_label' => 'ការកំណត់',
            'wf_staff_count' => ':count បុគ្គលិក',
            'wf_staff_hierarchy' => 'Hierarchy បុគ្គលិក',
            'wf_staff_org_sitemap' => 'ផែនទីរចនាសម្ព័ន្ធបុគ្គលិក',
            'wf_staff_org_sitemap_desc' => 'ផែនទីរចនាសម្ព័ន្ធសម្រាប់ការភ្ជាប់បុគ្គលិកទៅអ្នកគ្រប់គ្រង។',
            'wf_staff_supervisor_help' => 'សម្រាប់សំណើបុគ្គលិក បញ្ជូនទៅអ្នកគ្រប់គ្រងដែលបានផ្គូផ្គង។',
            'wf_staff_to_supervisor' => 'បុគ្គលិក -> អ្នកគ្រប់គ្រង',
            'wf_staff_under_who' => 'បុគ្គលិកនៅក្រោមអ្នកណា',
            'wf_step_number' => 'ជំហាន #:step',
            'wf_step_of' => 'ជំហាន :current នៃ :total',
            'wf_strategy' => 'យុទ្ធសាស្រ្ត',
            'wf_telegram_id' => 'Telegram ID',
            'wf_telegram_user_number' => 'អ្នកប្រើ Telegram #:id',
            'wf_workflow' => 'Workflow',
            'wf_workflow_status' => 'ស្ថានភាព Workflow',
            'wf_incoming_handlers_updated' => 'បានធ្វើបច្ចុប្បន្នភាពអ្នកទទួលសំណើចូល។',
            'wf_customer_owner_required' => 'ត្រូវការអតិថិជន និងម្ចាស់ទទួលខុសត្រូវ។',
            'wf_selected_customer_invalid' => 'អតិថិជនដែលបានជ្រើសមិនត្រឹមត្រូវ។',
            'wf_selected_owner_must_staff' => 'ម្ចាស់ដែលបានជ្រើសត្រូវតែជាបុគ្គលិក។',
            'wf_customer_owner_mapping_saved' => 'បានរក្សាទុកការផ្គូផ្គងអតិថិជនទៅម្ចាស់។',
            'wf_mapping_not_found' => 'រកមិនឃើញការផ្គូផ្គង។',
            'wf_customer_owner_mapping_deleted' => 'បានលុបការផ្គូផ្គងអតិថិជនទៅម្ចាស់។',
            'wf_user_supervisor_required' => 'ត្រូវការអ្នកប្រើ និងអ្នកគ្រប់គ្រង។',
            'wf_user_supervisor_same_error' => 'អ្នកប្រើ និងអ្នកគ្រប់គ្រងមិនអាចដូចគ្នាបានទេ។',
            'wf_selected_user_must_staff' => 'អ្នកប្រើដែលបានជ្រើសត្រូវតែជាបុគ្គលិក។',
            'wf_selected_supervisor_must_staff' => 'អ្នកគ្រប់គ្រងដែលបានជ្រើសត្រូវតែជាបុគ្គលិក។',
            'wf_user_reporting_mapping_saved' => 'បានរក្សាទុកការផ្គូផ្គងរាយការណ៍បុគ្គលិក។',
            'wf_reporting_mapping_not_found' => 'រកមិនឃើញការផ្គូផ្គងរាយការណ៍។',
            'wf_user_reporting_mapping_deleted' => 'បានលុបការផ្គូផ្គងរាយការណ៍បុគ្គលិក។',
            'wf_miniapp_profile_required' => 'ត្រូវការ Mini App profile។',
            'wf_miniapp_staff_profile_invalid' => 'Mini App staff profile ដែលបានជ្រើសមិនត្រឹមត្រូវ។',
            'wf_mapped_user_must_active_staff' => 'អ្នកប្រើដែលត្រូវផ្គូផ្គងត្រូវតែជាបុគ្គលិកសកម្ម។',
            'wf_miniapp_staff_mapping_saved' => 'បានរក្សាទុកការផ្គូផ្គងបុគ្គលិក Mini App។',
            'wf_miniapp_staff_mapping_cleared' => 'បានដកការផ្គូផ្គងបុគ្គលិក Mini App។',
            'wf_category_required' => 'ត្រូវការប្រភេទ។',
            'wf_invalid_routing_mode' => 'របៀប routing មិនត្រឹមត្រូវ។',
            'wf_invalid_queue_strategy' => 'យុទ្ធសាស្រ្ត queue មិនត្រឹមត្រូវ។',
            'wf_selected_category_invalid' => 'ប្រភេទដែលបានជ្រើសមិនត្រឹមត្រូវ។',
            'wf_department_required_for_queue' => 'ត្រូវការផ្នែកសម្រាប់ routing តាម department queue។',
            'wf_selected_department_invalid' => 'ផ្នែកដែលបានជ្រើសមិនត្រឹមត្រូវ។',
            'wf_category_routing_table_unavailable' => 'តារាង category routing មិនទាន់មានទេ។ សូមរត់ migrations ជាមុនសិន។',
            'wf_category_routing_saved' => 'បានរក្សាទុកច្បាប់ category routing។',
            'wf_category_routing_not_found' => 'រកមិនឃើញច្បាប់ category routing។',
            'wf_category_routing_deleted' => 'បានលុបច្បាប់ category routing។',
            'wf_template_created' => 'បានបង្កើត workflow template។',
            'wf_template_not_found' => 'រកមិនឃើញ workflow template។',
            'wf_template_updated' => 'បានធ្វើបច្ចុប្បន្នភាព workflow template។',
            'wf_template_delete_active_blocked' => 'មិនអាចលុប template ដែលមាន ticket workflow កំពុងដំណើរការបានទេ។',
            'wf_template_deleted' => 'បានលុប workflow template។',
            'wf_step_created' => 'បានបង្កើត workflow step។',
            'wf_step_create_failed' => 'បង្កើត step បរាជ័យ។ សូមពិនិត្យ step order និងទិន្នន័យដែលត្រូវការ។',
            'wf_step_not_found' => 'រកមិនឃើញ workflow step។',
            'wf_step_updated' => 'បានធ្វើបច្ចុប្បន្នភាព workflow step។',
            'wf_step_update_failed' => 'ធ្វើបច្ចុប្បន្នភាព step បរាជ័យ។ សូមពិនិត្យ step order និងទិន្នន័យដែលត្រូវការ។',
            'wf_step_deleted' => 'បានលុប workflow step។',
            'wf_template_name_required' => 'ត្រូវការឈ្មោះ template។',
            'wf_invalid_trigger_source' => 'Trigger source មិនត្រឹមត្រូវ។',
            'wf_invalid_trigger_category' => 'Trigger category មិនត្រឹមត្រូវ។',
            'wf_workflow_template_required' => 'ត្រូវការ workflow template។',
            'wf_selected_workflow_template_invalid' => 'Workflow template ដែលបានជ្រើសមិនត្រឹមត្រូវ។',
            'wf_step_order_name_required' => 'ត្រូវការ step order និងឈ្មោះ step។',
            'wf_sla_minutes_min_1' => 'SLA minutes ត្រូវតែយ៉ាងតិច 1។',
            'wf_invalid_approver_type' => 'Approver type មិនត្រឹមត្រូវ។',
            'wf_approver_user_required' => 'ត្រូវការ approver user សម្រាប់ user approver type។',
            'wf_approver_role_required' => 'ត្រូវការ role ត្រឹមត្រូវសម្រាប់ role approver type។',
            'wf_department_required_for_approver' => 'ត្រូវការផ្នែកសម្រាប់ department manager approver type។',
        ]);

        return $messages;
    }
}

if (!function_exists('__')) {
    function __(string $key, array $replace = []): string
    {
        $messages = translations();
        $lang = app_lang();
        $text = $messages[$lang][$key] ?? $messages['en'][$key] ?? $key;

        if (empty($replace)) {
            return $text;
        }

        $map = [];
        foreach ($replace as $k => $v) {
            $map[':' . $k] = (string) $v;
        }

        return strtr($text, $map);
    }
}
